spring.application.name=map_service

grpc.server.port=6003
grpc.server.security.enabled=true
grpc.server.security.certificate-chain=file:cert/dev-docker/tls.crt
grpc.server.security.private-key=file:cert/dev-docker/tls.key
grpc.server.security.client-auth=REQUIRE
grpc.server.security.trust-cert-collection=file:cert/dev-docker/ca.crt

spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://postgres:5432/map-service?sslmode=verify-full&sslrootcert=cert/dev-docker/ca.crt&sslcert=cert/dev-docker/tls.crt&sslkey=cert/dev-docker/tls-key.der
spring.datasource.host=postgres
spring.datasource.port=5433
spring.datasource.username=prisma
spring.datasource.password=prisma
spring.datasource.database=map-service
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.validation-timeout=2000
spring.datasource.hikari.connection-timeout=5000

management.server.port=35006
management.server.ssl.enabled=true
management.server.ssl.certificate=cert/dev-docker/tls.crt
management.server.ssl.certificate-private-key=cert/dev-docker/tls.key
management.server.ssl.client-auth=need
management.server.ssl.trust-certificate=cert/dev-docker/ca.crt

management.endpoints.web.exposure.include=health,prometheus
management.prometheus.metrics.export.enabled=true
management.metrics.distribution.percentiles-histogram[http.server.requests]=true
management.metrics.tags.application=map_service

app.datasource.database-name=map-service
