name: 'Check and build golang service'
description: 'Check and build golang service'

inputs:
  service-path:
    description: 'Path to service'
    required: true
  main-file-root-path:
    description: 'Path to modules'
    default: './cmd'
  with-migration:
    description: 'Run steps for migration'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
    - name: Install dependencies
      run: go mod download
      shell: bash
      working-directory: ${{ inputs.service-path }}
    - name: Build
      run: go build -o app ${{ inputs.main-file-root-path }}
      shell: bash
      working-directory: ${{ inputs.service-path }}
    - name: Build migration
      if: ${{ inputs.with-migration }}
      run: go build -o migration ./cmd/migration
      shell: bash
      working-directory: ${{ inputs.service-path }}
    - name: Lint
      run: go vet ${{ inputs.main-file-root-path }}
      shell: bash
      working-directory: ${{ inputs.service-path }}
    - name: Lint migration
      if: ${{ inputs.with-migration }}
      run: go vet ./cmd/migration
      shell: bash
      working-directory: ${{ inputs.service-path }}
