name: 'Check and build nestjs service'
description: 'Check and build nestjs service'

inputs:
  service-path:
    description: 'Path to service'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.service-path }}
    - name: Lint
      run: npm run lint
      working-directory: ${{ inputs.service-path }}
