// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/application/facade"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/domain/service/billing"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/domain/service/config"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/domain/service/connection"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/domain/service/jwt"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/domain/service/validator"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/infrastructure/database"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/infrastructure/repository_impl"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/infrastructure/service/billing_service_impl"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/infrastructure/service/config_impl"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/infrastructure/service/context"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/infrastructure/service/login_impl"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/infrastructure/service/tls"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/infrastructure/service/validator_impl"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/interface/grpc"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/interface/grpc/interceptor"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/interface/grpc/server"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/interface/http/fiber"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/internal/interface/http/middleware"
	"github.com/Stepasha419a/ducks-tinder-server/subscription-service/proto/gen"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func newContainer() (*Container, func(), error) {
	context, cleanup := context_service.NewContext()
	validatorServiceImpl := validator_service_impl.NewValidatorService()
	configServiceImpl := config_service_impl.NewConfigService(validatorServiceImpl)
	jwtService := jwt_service.NewJwtService(configServiceImpl)
	middlewareMiddleware := middleware.NewMiddleware(jwtService)
	tlsService := tls_service.NewTlsService(configServiceImpl)
	connectionService := connection_service.NewConnectionService()
	postgres, cleanup2 := database.NewPostgresInstance(context, configServiceImpl, tlsService, connectionService)
	subscriptionRepositoryImpl := repository_impl.NewSubscriptionRepository(postgres)
	loginServiceImpl := login_service_impl.NewLoginServiceImpl(configServiceImpl)
	billingServiceImpl, cleanup3 := billing_service_impl.NewBillingServiceImpl(context, configServiceImpl, tlsService, connectionService)
	subscriptionFacade := facade.NewSubscriptionFacade(subscriptionRepositoryImpl, loginServiceImpl, billingServiceImpl)
	httpFiberApp, cleanup4 := fiber_impl.NewHttpFiberApp(middlewareMiddleware, subscriptionFacade, configServiceImpl, validatorServiceImpl)
	healthFiberApp, cleanup5 := fiber_impl.NewHealthFiberApp(configServiceImpl, connectionService)
	subscriptionServiceServerImpl := grpc_subscription_service_server_impl.NewSubscriptionServiceServerImpl(subscriptionFacade, validatorServiceImpl)
	grpcInterceptor := grpc_interceptor.NewInterceptor(jwtService)
	server, cleanup6 := grpc_interface.NewGrpc(subscriptionServiceServerImpl, grpcInterceptor, tlsService, configServiceImpl)
	container := &Container{
		Context:                   context,
		ValidatorService:          validatorServiceImpl,
		ConfigService:             configServiceImpl,
		HttpFiberApp:              httpFiberApp,
		HealthFiberApp:            healthFiberApp,
		SubscriptionServiceServer: subscriptionServiceServerImpl,
		TlsService:                tlsService,
		GrpcServer:                server,
		BillingService:            billingServiceImpl,
	}
	return container, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type Container struct {
	Context                   context.Context
	ValidatorService          validator_service.ValidatorService
	ConfigService             config_service.ConfigService
	HttpFiberApp              *fiber_impl.HttpFiberApp
	HealthFiberApp            *fiber_impl.HealthFiberApp
	SubscriptionServiceServer gen.SubscriptionServiceServer
	TlsService                *tls_service.TlsService
	GrpcServer                *grpc.Server
	BillingService            billing_service.BillingService
}
