global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'user-service'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/cert/dev-docker/certificate.pem
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'chat-service'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/cert/dev-docker/certificate.pem
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: 'file-service'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/cert/dev-docker/certificate.pem
    static_configs:
      - targets: ['host.docker.internal:5002']

  - job_name: 'auth-service'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/cert/dev-docker/certificate.pem
    static_configs:
      - targets: ['host.docker.internal:5003']

  - job_name: 'billing-service'
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/cert/dev-docker/certificate.pem
    static_configs:
      - targets: ['host.docker.internal:5004']
