global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'chat-service'
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: 'file-service'
    static_configs:
      - targets: ['host.docker.internal:5002']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:5003']

  - job_name: 'billing-service'
    static_configs:
      - targets: ['host.docker.internal:5004']
