apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheusdatasource
    access: proxy
    orgId: 1
    url: https://prometheus:9090
    password:
    user:
    database:
    basicAuth: false
    basicAuthUser:
    basicAuthPassword:
    withCredentials:
    isDefault: true
    jsonData:
      graphiteVersion: '1.1'
      tlsAuth: true
      tlsAuthWithCACert: true
      tlsSkipVerify: false
    secureJsonData:
      tlsCACert: $__file{/etc/grafana/cert/dev-docker/ca.crt}
      tlsClientCert: $__file{/etc/grafana/cert/dev-docker/certificate.pem}
      tlsClientKey: $__file{/etc/grafana/cert/dev-docker/private-key.pem}
    version: 1
    editable: true
