apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor-deployment
  labels:
    app: cadvisor-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor-app-deployment
  template:
    metadata:
      labels:
        app: cadvisor-app-deployment
    spec:
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.52.1
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /var/run
              name: var-run
            - mountPath: /sys
              name: sys
            - mountPath: /var/lib/docker
              name: var-lib-docker
            - mountPath: /cgroup
              name: cgroup
          args:
            - '--port=8080'
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: var-lib-docker
          hostPath:
            path: /var/lib/docker
        - name: cgroup
          hostPath:
            path: /cgroup
