apiVersion: v1
kind: Service
metadata:
  name: cadvisor-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: '30'
spec:
  type: ClusterIP
  selector:
    app: cadvisor-app-deployment
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
