apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  labels:
    app: chat-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-service-deployment
  template:
    metadata:
      labels:
        app: chat-app-service-deployment
    spec:
      initContainers:
        - name: chat-service-instance
          image: 10.98.141.40:80/ducks-tinder-chat-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '96Mi'
            requests:
              cpu: '0.125'
              memory: '96Mi'
          env:
            - name: NODE_ENV
              value: 'dev-k8s'
            - name: DATABASE_URL
              value: 'postgresql://postgres:prisma@postgres-postgresql:5432/tinder'
          command: ['sh', '-c', 'npx prisma migrate deploy']
      containers:
        - name: chat-app-service-deployment
          image: 10.98.141.40:80/ducks-tinder-chat-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '96Mi'
            requests:
              cpu: '0.125'
              memory: '96Mi'
          env:
            - name: NODE_ENV
              value: 'dev-k8s'
          ports:
            - name: http
              containerPort: 5001
