apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  labels:
    app: chat-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-service-deployment
  template:
    metadata:
      labels:
        app: chat-app-service-deployment
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 70
      initContainers:
        - name: chat-service-instance
          image: 10.98.141.40:80/ducks-tinder-chat-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '96Mi'
            requests:
              cpu: '0.125'
              memory: '96Mi'
          env:
            - name: NODE_ENV
              value: 'dev-k8s'
            - name: DATABASE_URL
              value: 'postgresql://postgres:prisma@postgres-postgresql:5432/tinder'
          command: ['sh', '-c', 'npx prisma migrate deploy']
      containers:
        - name: chat-app-service-deployment
          image: 10.98.141.40:80/ducks-tinder-chat-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '96Mi'
            requests:
              cpu: '0.125'
              memory: '96Mi'
          env:
            - name: NODE_ENV
              value: 'dev-k8s'
          ports:
            - name: http
              containerPort: 5001
          volumeMounts:
            - name: tls-volume
              mountPath: /usr/src/app/cert/dev-k8s
              readOnly: true
            - name: config-volume
              mountPath: /usr/src/app/.env.dev-k8s
              subPath: .env.dev-k8s
              readOnly: true
      volumes:
        - name: tls-volume
          secret:
            secretName: common-ca-tls-secret
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
                mode: 0640
              - key: ca.crt
                path: ca.crt
        - name: config-volume
          secret:
            secretName: chat-service-secret
