apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  labels:
    app: chat-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-service-deployment
  template:
    metadata:
      labels:
        app: chat-app-service-deployment
    spec:
