apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: common-ca
spec:
  secretName: common-ca-tls-secret
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: postgres
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    encoding: PKCS8
