apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: common-ca
spec:
  secretName: common-ca-tls-secret
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus-service
    - grafana-service
    - auth-service-service
    - billing-service-service
    - subscription-service-service
    - user-service-service
    - chat-service-service
    - file-service-service
    - map-service-service
    - rabbitmq-service
    - postgres-service
  commonName: postgres
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
    encoding: PKCS8
