apiVersion: v1
kind: Service
metadata:
  name: file-service-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: '30'
spec:
  type: ClusterIP
  selector:
    app: file-app-service-deployment
  ports:
    - name: http
      port: 5002
      targetPort: 5002
      protocol: TCP
    - name: grpc
      port: 6000
      targetPort: 6000
      protocol: TCP
