apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service-deployment
  labels:
    app: file-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-app-service-deployment
  template:
    metadata:
      labels:
        app: file-app-service-deployment
    spec:
      containers:
        - name: file-app-service-deployment
          image: 10.98.141.40:80/ducks-tinder-file-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '64Mi'
            requests:
              cpu: '0.125'
              memory: '64Mi'
          env:
            - name: MODE
              value: 'dev-k8s'
          ports:
            - name: http
              containerPort: 5002
            - name: grpc
              containerPort: 6000
          volumeMounts:
            - name: file-service-media
              mountPath: ../static
