apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app-deployment
  template:
    metadata:
      labels:
        app: grafana-app-deployment
    spec:
      containers:
        - name: grafana-app-deployment
          image: grafana/grafana:11.4.0
          ports:
            - name: http
              containerPort: 9100
