apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksm-role-binging
subjects:
  - kind: ServiceAccount
    name: ksm-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: ksm-role
  apiGroup: rbac.authorization.k8s.io
