apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksm-deployment
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.15.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksm-app-deployment
  template:
    metadata:
      labels:
        app: ksm-app-deployment
