apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-dashboards-config
    files:
      - dashboards/auth-service-dashboard.json
      - dashboards/billing-service-dashboard.json
      - dashboards/chat-service-dashboard.json
      - dashboards/dashboard.yml
      - dashboards/file-service-dashboard.json
      - dashboards/map-service-dashboard.json
      - dashboards/subscription-service-dashboard.json
      - dashboards/user-service-dashboard.json
      - dashboards/postgres.json
      - dashboards/rabbitmq.json
      - dashboards/kube-state-dashboard.json
  - name: grafana-dashboards-config-2
    files:
      - dashboards/cadvisor-dashboard.json
      - dashboards/node-exporter-dashboard.json

secretGenerator:
  - name: user-service-secret
    files:
      - .env.dev-k8s=user-service-secret-template.env
    type: Opaque
  - name: chat-service-secret
    files:
      - .env.dev-k8s=chat-service-secret-template.env
    type: Opaque
  - name: file-service-secret
    files:
      - dev-k8s.yaml=file-service-secret-template.yaml
    type: Opaque
  - name: auth-service-secret
    files:
      - dev-k8s.yaml=auth-service-secret-template.yaml
    type: Opaque
  - name: billing-service-secret
    files:
      - dev-k8s.yaml=billing-service-secret-template.yaml
    type: Opaque
  - name: subscription-service-secret
    files:
      - dev-k8s.yaml=subscription-service-secret-template.yaml
    type: Opaque
  - name: map-service-secret
    files:
      - application-dev-k8s.properties=map-service-secret-template.properties
    type: Opaque

  - name: grafana-secret
    literals:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_HTTP_PORT=3000
      - GF_INSTALL_PLUGINS=
      - GF_SERVER_ROOT_URL=https://kubernetes.docker.internal/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/cert/tls.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/cert/tls.key
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
