apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-dashboards-config
    files:
      - dashboards/auth-service-dashboard.json
      - dashboards/billing-service-dashboard.json
      - dashboards/chat-service-dashboard.json
      - dashboards/dashboard.yml
      - dashboards/file-service-dashboard.json
      - dashboards/map-service-dashboard.json
      - dashboards/subscription-service-dashboard.json
      - dashboards/user-service-dashboard.json
      - dashboards/postgres.json
      - dashboards/rabbitmq.json
      - dashboards/kube-state-dashboard.json
  - name: grafana-dashboards-config-2
    files:
      - dashboards/cadvisor-dashboard.json
      - dashboards/node-exporter-dashboard.json

secretGenerator:
  - name: user-service-secret
    files:
      - .env.dev-k8s=user-service-secret-template.env
    type: Opaque
  - name: chat-service-secret
    files:
      - .env.dev-k8s=chat-service-secret-template.env
    type: Opaque
  - name: auth-service-secret
    files:
      - dev-k8s.yaml=auth-service-secret-template.yaml
    type: Opaque
  - name: billing-service-secret
    files:
      - dev-k8s.yaml=billing-service-secret-template.yaml
    type: Opaque
  - name: subscription-service-secret
    files:
      - dev-k8s.yaml=subscription-service-secret-template.yaml
    type: Opaque
  - name: map-service-secret
    files:
      - application-dev-k8s.properties=map-service-secret-template.properties
    type: Opaque
