apiVersion: v1
kind: Service
metadata:
  name: map-service-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: '30'
spec:
  type: ClusterIP
  selector:
    app: map-app-service-deployment
  ports:
    - name: http
      port: 5006
      targetPort: 5006
      protocol: TCP
    - name: grpc
      port: 6003
      targetPort: 6003
      protocol: TCP
