apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-service-deployment
  labels:
    app: map-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-app-service-deployment
  template:
    metadata:
      labels:
        app: map-app-service-deployment
    spec:
