apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter-deployment
  labels:
    app: node-exporter-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter-app-deployment
  template:
    metadata:
      labels:
        app: node-exporter-app-deployment
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: node-exporter-app-deployment
          image: quay.io/prometheus/node-exporter:v1.9.1
          ports:
            - containerPort: 9100
          args:
            - '--path.rootfs=/host'
          volumeMounts:
            - name: host-root
              mountPath: /host
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
