apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
spec:
  type: ClusterIP
  selector:
    app: node-exporter-app-deployment
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
