apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 30s

    scrape_configs:
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-postgresql-metrics:9187']
      
      - job_name: 'file-service'
        scheme: https
        tls_config:
          ca_file: /etc/prometheus/cert/ca.crt
          cert_file: /etc/prometheus/cert/tls.crt
          key_file: /etc/prometheus/cert/tls.key
        static_configs:
          - targets: ['file-service-service:5002']
      - job_name: 'auth-service'
        scheme: https
        tls_config:
          ca_file: /etc/prometheus/cert/ca.crt
          cert_file: /etc/prometheus/cert/tls.crt
          key_file: /etc/prometheus/cert/tls.key
        static_configs:
          - targets: ['auth-service-service:5003']
      - job_name: 'billing-service'
        scheme: https
        tls_config:
          ca_file: /etc/prometheus/cert/ca.crt
          cert_file: /etc/prometheus/cert/tls.crt
          key_file: /etc/prometheus/cert/tls.key
        static_configs:
          - targets: ['billing-service-service:5004']
      - job_name: 'subscription-service'
        scheme: https
        tls_config:
          ca_file: /etc/prometheus/cert/ca.crt
          cert_file: /etc/prometheus/cert/tls.crt
          key_file: /etc/prometheus/cert/tls.key
        static_configs:
          - targets: ['subscription-service-service:5005']
      - job_name: 'map-service'
        scheme: https
        tls_config:
          ca_file: /etc/prometheus/cert/ca.crt
          cert_file: /etc/prometheus/cert/tls.crt
          key_file: /etc/prometheus/cert/tls.key
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['map-service-service:5006']
  web-config.yml: |
    tls_server_config:
      cert_file: /etc/prometheus/cert/tls.crt
      key_file: /etc/prometheus/cert/tls.key
