apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-role
rules:
  - apiGroups: ['']
    resources:
      - nodes
      - pods
      - services
      - endpoints
    verbs: ['get', 'list', 'watch']
