apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 30s
  web-config.yml: |
    tls_server_config:
      cert_file: /etc/prometheus/cert/tls.crt
      key_file: /etc/prometheus/cert/tls.key
