apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  nginx.conf: |
    events {}

    http {
        server {

            listen 7000 ssl;

            ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
            ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

            location /user {
              proxy_pass https://user-service-service:5000;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /chat {
              proxy_pass https://chat-service-service:5001;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /file/ {
              proxy_pass https://file-service-service:5002/;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /auth {
              proxy_pass https://auth-service-service:5003;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /billing {
              proxy_pass https://billing-service-service:5004;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /subscription {
              proxy_pass https://subscription-service-service:5005;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /prometheus {
              proxy_pass https://prometheus-server:9090;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /grafana {
              proxy_pass https://grafana:80;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /rabbitmq/ {
              proxy_pass https://rabbitmq:15672/;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }
        }
    }
