apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  nginx.conf: |
    events {}

    http {
        server {

            listen 7000 ssl;

            ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
            ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

            location /user {
              proxy_pass https://user-service-service:5000;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }

            location /chat {
              proxy_pass https://chat-service-service:5001;
              proxy_http_version 1.1;

              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Connection "upgrade";

              proxy_ssl_certificate     /etc/nginx/cert/dev-k8s/tls.crt;
              proxy_ssl_certificate_key /etc/nginx/cert/dev-k8s/tls.key;

              proxy_cache_bypass $http_upgrade;
            }
              proxy_cache_bypass $http_upgrade;
            }
        }
    }
