apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-app-deployment
  template:
    metadata:
      labels:
        app: rabbitmq-app-deployment
    spec:
      containers:
        - name: rabbitmq-app-deployment
          image: rabbitmq:4-management
          resources:
            limits:
              cpu: '0.0625'
              memory: '128Mi'
            requests:
              cpu: '0.0625'
              memory: '128Mi'
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
            - name: tls-volume
              mountPath: /etc/rabbitmq/cert
              readOnly: true
            - name: data-volume
              mountPath: /var/lib/rabbitmq
          env:
            - name: RABBITMQ_CONFIG_FILE
              value: /etc/rabbitmq/rabbitmq
      volumes:
        - name: config-volume
          configMap:
            name: rabbitmq-config
        - name: tls-volume
          secret:
            secretName: common-ca-tls-secret
        - name: data-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
