mode: dev-k8s
jwt_access_secret: df345sdfsdfas234dfasdfa567sdf
jwt_subscription_service_secret: as234da234sds456df
jwt_billing_service_secret: dfgh567sdfgdfg456sdfgdfg
port: 443
health_port: 3443
grpc_port: 50051
client_url: http://localhost:3000
grpc_billing_service_url: billing-service-service:50051
grpc_billing_service_domain: billing-service-service
login_service_url: https://api.github.com/repos/Stepasha419a/ducks-tinder-client/stargazers
tls_server_name: subscription-service-service
postgres_host: postgres-service
postgres_port: 5432
postgres_user: postgres
postgres_password: prisma
postgres_database: subscription-service
