apiVersion: v1
kind: Service
metadata:
  name: subscription-service-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: '30'
spec:
  type: ClusterIP
  selector:
    app: subscription-app-service-deployment
  ports:
    - name: http
      port: 5005
      targetPort: 5005
      protocol: TCP
    - name: grpc
      port: 6002
      targetPort: 6002
      protocol: TCP
