apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service-deployment
  labels:
    app: subscription-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-app-service-deployment
  template:
    metadata:
      labels:
        app: subscription-app-service-deployment
    spec:
      initContainers:
        - name: subscription-service-instance
          image: 10.98.141.40:80/ducks-tinder-subscription-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '64Mi'
            requests:
              cpu: '0.0625'
              memory: '32Mi'
          env:
            - name: MODE
              value: 'dev-k8s'
          command: ['/usr/src/app/migration', '-auto-submit']
          volumeMounts:
            - name: tls-volume
              mountPath: /usr/src/app/cert/dev-k8s
              readOnly: true
            - name: config-volume
              mountPath: /usr/src/app/config
              readOnly: true
      containers:
        - name: subscription-app-service-deployment
          image: 10.98.141.40:80/ducks-tinder-subscription-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '64Mi'
            requests:
              cpu: '0.0625'
              memory: '32Mi'
          env:
            - name: MODE
              value: 'dev-k8s'
          ports:
            - name: http
              containerPort: 5005
            - name: grpc
              containerPort: 6002
          command:
            - '/usr/src/app/app'
          volumeMounts:
            - name: tls-volume
              mountPath: /usr/src/app/cert/dev-k8s
              readOnly: true
            - name: config-volume
              mountPath: /usr/src/app/config
              readOnly: true
      volumes:
        - name: tls-volume
          secret:
            secretName: common-ca-tls-secret
        - name: config-volume
          secret:
            secretName: subscription-service-secret
