apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: '30'
spec:
  type: ClusterIP
  selector:
    app: user-app-service-deployment
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
