apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app-service-deployment
  template:
    metadata:
      labels:
        app: user-app-service-deployment
    spec:
      initContainers:
        - name: user-service-instance
          image: 10.98.141.40:80/ducks-tinder-user-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '96Mi'
            requests:
              cpu: '0.125'
              memory: '96Mi'
          env:
            - name: NODE_ENV
              value: 'dev-k8s'
            - name: IS_MIGRATION
              value: 'true'
            - name: MIGRATION_DB_NAME
              value: 'tinder'
            - name: DATABASE_URL
              value: 'postgresql://postgres:prisma@postgres-postgresql:5432/tinder'
          command: ['sh', '-c', 'npx prisma migrate deploy']
      containers:
        - name: user-app-service-deployment
          image: 10.98.141.40:80/ducks-tinder-user-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.125'
              memory: '96Mi'
            requests:
              cpu: '0.125'
              memory: '96Mi'
          env:
            - name: NODE_ENV
              value: 'dev-k8s'
          ports:
            - name: http
              containerPort: 5000
