GRPC_JAVA_PLUGIN = C:/apps/protoc-gen-grpc-java-1.60.0-windows-x86_64/protoc-gen-grpc-java-1.60.0-windows-x86_64.exe

dev:
	mvn spring-boot:run -Dspring-boot.run.profiles=dev

migration:
	mvn clean install