
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  CheckedUsers: 'CheckedUsers',
  Place: 'Place',
  Picture: 'Picture',
  UsersOnInterests: 'UsersOnInterests',
  Message: 'Message',
  Chat: 'Chat',
  UsersOnChats: 'UsersOnChats'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  nickname: 'nickname',
  isActivated: 'isActivated',
  age: 'age',
  sex: 'sex',
  distance: 'distance',
  usersOnlyInDistance: 'usersOnlyInDistance',
  preferSex: 'preferSex',
  preferAgeFrom: 'preferAgeFrom',
  preferAgeTo: 'preferAgeTo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastReturnableId: 'lastReturnableId',
  zodiacSign: 'zodiacSign',
  education: 'education',
  childrenAttitude: 'childrenAttitude',
  personalityType: 'personalityType',
  communicationStyle: 'communicationStyle',
  attentionSign: 'attentionSign',
  pet: 'pet',
  alcoholAttitude: 'alcoholAttitude',
  smokingAttitude: 'smokingAttitude',
  trainingAttitude: 'trainingAttitude',
  foodPreference: 'foodPreference',
  socialNetworksActivity: 'socialNetworksActivity',
  chronotype: 'chronotype'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CheckedUsersScalarFieldEnum = {
  checkedId: 'checkedId',
  wasCheckedId: 'wasCheckedId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CheckedUsersScalarFieldEnum = (typeof CheckedUsersScalarFieldEnum)[keyof typeof CheckedUsersScalarFieldEnum]


export const PlaceScalarFieldEnum = {
  id: 'id',
  latitude: 'latitude',
  longitude: 'longitude',
  name: 'name',
  address: 'address',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlaceScalarFieldEnum = (typeof PlaceScalarFieldEnum)[keyof typeof PlaceScalarFieldEnum]


export const PictureScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  order: 'order',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PictureScalarFieldEnum = (typeof PictureScalarFieldEnum)[keyof typeof PictureScalarFieldEnum]


export const UsersOnInterestsScalarFieldEnum = {
  interest: 'interest',
  userId: 'userId'
} as const

export type UsersOnInterestsScalarFieldEnum = (typeof UsersOnInterestsScalarFieldEnum)[keyof typeof UsersOnInterestsScalarFieldEnum]


export const MessageScalarFieldEnum = {
  id: 'id',
  text: 'text',
  userId: 'userId',
  chatId: 'chatId',
  repliedId: 'repliedId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MessageScalarFieldEnum = (typeof MessageScalarFieldEnum)[keyof typeof MessageScalarFieldEnum]


export const ChatScalarFieldEnum = {
  id: 'id',
  blocked: 'blocked',
  blockedById: 'blockedById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ChatScalarFieldEnum = (typeof ChatScalarFieldEnum)[keyof typeof ChatScalarFieldEnum]


export const UsersOnChatsScalarFieldEnum = {
  chatId: 'chatId',
  userId: 'userId',
  newMessagesCount: 'newMessagesCount',
  createdAt: 'createdAt',
  lastSeenAt: 'lastSeenAt'
} as const

export type UsersOnChatsScalarFieldEnum = (typeof UsersOnChatsScalarFieldEnum)[keyof typeof UsersOnChatsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

