
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CheckedUsers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CheckedUsers
 * 
 */
export type CheckedUsersModel = runtime.Types.Result.DefaultSelection<Prisma.$CheckedUsersPayload>

export type AggregateCheckedUsers = {
  _count: CheckedUsersCountAggregateOutputType | null
  _min: CheckedUsersMinAggregateOutputType | null
  _max: CheckedUsersMaxAggregateOutputType | null
}

export type CheckedUsersMinAggregateOutputType = {
  checkedId: string | null
  wasCheckedId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CheckedUsersMaxAggregateOutputType = {
  checkedId: string | null
  wasCheckedId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CheckedUsersCountAggregateOutputType = {
  checkedId: number
  wasCheckedId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CheckedUsersMinAggregateInputType = {
  checkedId?: true
  wasCheckedId?: true
  createdAt?: true
  updatedAt?: true
}

export type CheckedUsersMaxAggregateInputType = {
  checkedId?: true
  wasCheckedId?: true
  createdAt?: true
  updatedAt?: true
}

export type CheckedUsersCountAggregateInputType = {
  checkedId?: true
  wasCheckedId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CheckedUsersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CheckedUsers to aggregate.
   */
  where?: Prisma.CheckedUsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckedUsers to fetch.
   */
  orderBy?: Prisma.CheckedUsersOrderByWithRelationInput | Prisma.CheckedUsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CheckedUsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckedUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckedUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CheckedUsers
  **/
  _count?: true | CheckedUsersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CheckedUsersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CheckedUsersMaxAggregateInputType
}

export type GetCheckedUsersAggregateType<T extends CheckedUsersAggregateArgs> = {
      [P in keyof T & keyof AggregateCheckedUsers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCheckedUsers[P]>
    : Prisma.GetScalarType<T[P], AggregateCheckedUsers[P]>
}




export type CheckedUsersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckedUsersWhereInput
  orderBy?: Prisma.CheckedUsersOrderByWithAggregationInput | Prisma.CheckedUsersOrderByWithAggregationInput[]
  by: Prisma.CheckedUsersScalarFieldEnum[] | Prisma.CheckedUsersScalarFieldEnum
  having?: Prisma.CheckedUsersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CheckedUsersCountAggregateInputType | true
  _min?: CheckedUsersMinAggregateInputType
  _max?: CheckedUsersMaxAggregateInputType
}

export type CheckedUsersGroupByOutputType = {
  checkedId: string
  wasCheckedId: string
  createdAt: Date
  updatedAt: Date
  _count: CheckedUsersCountAggregateOutputType | null
  _min: CheckedUsersMinAggregateOutputType | null
  _max: CheckedUsersMaxAggregateOutputType | null
}

type GetCheckedUsersGroupByPayload<T extends CheckedUsersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CheckedUsersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CheckedUsersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CheckedUsersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CheckedUsersGroupByOutputType[P]>
      }
    >
  >



export type CheckedUsersWhereInput = {
  AND?: Prisma.CheckedUsersWhereInput | Prisma.CheckedUsersWhereInput[]
  OR?: Prisma.CheckedUsersWhereInput[]
  NOT?: Prisma.CheckedUsersWhereInput | Prisma.CheckedUsersWhereInput[]
  checkedId?: Prisma.StringFilter<"CheckedUsers"> | string
  wasCheckedId?: Prisma.StringFilter<"CheckedUsers"> | string
  createdAt?: Prisma.DateTimeFilter<"CheckedUsers"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckedUsers"> | Date | string
  checked?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  wasChecked?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type CheckedUsersOrderByWithRelationInput = {
  checkedId?: Prisma.SortOrder
  wasCheckedId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  checked?: Prisma.UserOrderByWithRelationInput
  wasChecked?: Prisma.UserOrderByWithRelationInput
}

export type CheckedUsersWhereUniqueInput = Prisma.AtLeast<{
  checkedId_wasCheckedId?: Prisma.CheckedUsersCheckedIdWasCheckedIdCompoundUniqueInput
  AND?: Prisma.CheckedUsersWhereInput | Prisma.CheckedUsersWhereInput[]
  OR?: Prisma.CheckedUsersWhereInput[]
  NOT?: Prisma.CheckedUsersWhereInput | Prisma.CheckedUsersWhereInput[]
  checkedId?: Prisma.StringFilter<"CheckedUsers"> | string
  wasCheckedId?: Prisma.StringFilter<"CheckedUsers"> | string
  createdAt?: Prisma.DateTimeFilter<"CheckedUsers"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckedUsers"> | Date | string
  checked?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  wasChecked?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "checkedId_wasCheckedId">

export type CheckedUsersOrderByWithAggregationInput = {
  checkedId?: Prisma.SortOrder
  wasCheckedId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CheckedUsersCountOrderByAggregateInput
  _max?: Prisma.CheckedUsersMaxOrderByAggregateInput
  _min?: Prisma.CheckedUsersMinOrderByAggregateInput
}

export type CheckedUsersScalarWhereWithAggregatesInput = {
  AND?: Prisma.CheckedUsersScalarWhereWithAggregatesInput | Prisma.CheckedUsersScalarWhereWithAggregatesInput[]
  OR?: Prisma.CheckedUsersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CheckedUsersScalarWhereWithAggregatesInput | Prisma.CheckedUsersScalarWhereWithAggregatesInput[]
  checkedId?: Prisma.StringWithAggregatesFilter<"CheckedUsers"> | string
  wasCheckedId?: Prisma.StringWithAggregatesFilter<"CheckedUsers"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CheckedUsers"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CheckedUsers"> | Date | string
}

export type CheckedUsersCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  checked: Prisma.UserCreateNestedOneWithoutCheckedInput
  wasChecked: Prisma.UserCreateNestedOneWithoutWasCheckedInput
}

export type CheckedUsersUncheckedCreateInput = {
  checkedId: string
  wasCheckedId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CheckedUsersUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  checked?: Prisma.UserUpdateOneRequiredWithoutCheckedNestedInput
  wasChecked?: Prisma.UserUpdateOneRequiredWithoutWasCheckedNestedInput
}

export type CheckedUsersUncheckedUpdateInput = {
  checkedId?: Prisma.StringFieldUpdateOperationsInput | string
  wasCheckedId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckedUsersCreateManyInput = {
  checkedId: string
  wasCheckedId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CheckedUsersUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckedUsersUncheckedUpdateManyInput = {
  checkedId?: Prisma.StringFieldUpdateOperationsInput | string
  wasCheckedId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckedUsersListRelationFilter = {
  every?: Prisma.CheckedUsersWhereInput
  some?: Prisma.CheckedUsersWhereInput
  none?: Prisma.CheckedUsersWhereInput
}

export type CheckedUsersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CheckedUsersCheckedIdWasCheckedIdCompoundUniqueInput = {
  checkedId: string
  wasCheckedId: string
}

export type CheckedUsersCountOrderByAggregateInput = {
  checkedId?: Prisma.SortOrder
  wasCheckedId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckedUsersMaxOrderByAggregateInput = {
  checkedId?: Prisma.SortOrder
  wasCheckedId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckedUsersMinOrderByAggregateInput = {
  checkedId?: Prisma.SortOrder
  wasCheckedId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CheckedUsersCreateNestedManyWithoutCheckedInput = {
  create?: Prisma.XOR<Prisma.CheckedUsersCreateWithoutCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput> | Prisma.CheckedUsersCreateWithoutCheckedInput[] | Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput[]
  connectOrCreate?: Prisma.CheckedUsersCreateOrConnectWithoutCheckedInput | Prisma.CheckedUsersCreateOrConnectWithoutCheckedInput[]
  createMany?: Prisma.CheckedUsersCreateManyCheckedInputEnvelope
  connect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
}

export type CheckedUsersCreateNestedManyWithoutWasCheckedInput = {
  create?: Prisma.XOR<Prisma.CheckedUsersCreateWithoutWasCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput> | Prisma.CheckedUsersCreateWithoutWasCheckedInput[] | Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput[]
  connectOrCreate?: Prisma.CheckedUsersCreateOrConnectWithoutWasCheckedInput | Prisma.CheckedUsersCreateOrConnectWithoutWasCheckedInput[]
  createMany?: Prisma.CheckedUsersCreateManyWasCheckedInputEnvelope
  connect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
}

export type CheckedUsersUncheckedCreateNestedManyWithoutCheckedInput = {
  create?: Prisma.XOR<Prisma.CheckedUsersCreateWithoutCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput> | Prisma.CheckedUsersCreateWithoutCheckedInput[] | Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput[]
  connectOrCreate?: Prisma.CheckedUsersCreateOrConnectWithoutCheckedInput | Prisma.CheckedUsersCreateOrConnectWithoutCheckedInput[]
  createMany?: Prisma.CheckedUsersCreateManyCheckedInputEnvelope
  connect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
}

export type CheckedUsersUncheckedCreateNestedManyWithoutWasCheckedInput = {
  create?: Prisma.XOR<Prisma.CheckedUsersCreateWithoutWasCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput> | Prisma.CheckedUsersCreateWithoutWasCheckedInput[] | Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput[]
  connectOrCreate?: Prisma.CheckedUsersCreateOrConnectWithoutWasCheckedInput | Prisma.CheckedUsersCreateOrConnectWithoutWasCheckedInput[]
  createMany?: Prisma.CheckedUsersCreateManyWasCheckedInputEnvelope
  connect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
}

export type CheckedUsersUpdateManyWithoutCheckedNestedInput = {
  create?: Prisma.XOR<Prisma.CheckedUsersCreateWithoutCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput> | Prisma.CheckedUsersCreateWithoutCheckedInput[] | Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput[]
  connectOrCreate?: Prisma.CheckedUsersCreateOrConnectWithoutCheckedInput | Prisma.CheckedUsersCreateOrConnectWithoutCheckedInput[]
  upsert?: Prisma.CheckedUsersUpsertWithWhereUniqueWithoutCheckedInput | Prisma.CheckedUsersUpsertWithWhereUniqueWithoutCheckedInput[]
  createMany?: Prisma.CheckedUsersCreateManyCheckedInputEnvelope
  set?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  disconnect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  delete?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  connect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  update?: Prisma.CheckedUsersUpdateWithWhereUniqueWithoutCheckedInput | Prisma.CheckedUsersUpdateWithWhereUniqueWithoutCheckedInput[]
  updateMany?: Prisma.CheckedUsersUpdateManyWithWhereWithoutCheckedInput | Prisma.CheckedUsersUpdateManyWithWhereWithoutCheckedInput[]
  deleteMany?: Prisma.CheckedUsersScalarWhereInput | Prisma.CheckedUsersScalarWhereInput[]
}

export type CheckedUsersUpdateManyWithoutWasCheckedNestedInput = {
  create?: Prisma.XOR<Prisma.CheckedUsersCreateWithoutWasCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput> | Prisma.CheckedUsersCreateWithoutWasCheckedInput[] | Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput[]
  connectOrCreate?: Prisma.CheckedUsersCreateOrConnectWithoutWasCheckedInput | Prisma.CheckedUsersCreateOrConnectWithoutWasCheckedInput[]
  upsert?: Prisma.CheckedUsersUpsertWithWhereUniqueWithoutWasCheckedInput | Prisma.CheckedUsersUpsertWithWhereUniqueWithoutWasCheckedInput[]
  createMany?: Prisma.CheckedUsersCreateManyWasCheckedInputEnvelope
  set?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  disconnect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  delete?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  connect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  update?: Prisma.CheckedUsersUpdateWithWhereUniqueWithoutWasCheckedInput | Prisma.CheckedUsersUpdateWithWhereUniqueWithoutWasCheckedInput[]
  updateMany?: Prisma.CheckedUsersUpdateManyWithWhereWithoutWasCheckedInput | Prisma.CheckedUsersUpdateManyWithWhereWithoutWasCheckedInput[]
  deleteMany?: Prisma.CheckedUsersScalarWhereInput | Prisma.CheckedUsersScalarWhereInput[]
}

export type CheckedUsersUncheckedUpdateManyWithoutCheckedNestedInput = {
  create?: Prisma.XOR<Prisma.CheckedUsersCreateWithoutCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput> | Prisma.CheckedUsersCreateWithoutCheckedInput[] | Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput[]
  connectOrCreate?: Prisma.CheckedUsersCreateOrConnectWithoutCheckedInput | Prisma.CheckedUsersCreateOrConnectWithoutCheckedInput[]
  upsert?: Prisma.CheckedUsersUpsertWithWhereUniqueWithoutCheckedInput | Prisma.CheckedUsersUpsertWithWhereUniqueWithoutCheckedInput[]
  createMany?: Prisma.CheckedUsersCreateManyCheckedInputEnvelope
  set?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  disconnect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  delete?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  connect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  update?: Prisma.CheckedUsersUpdateWithWhereUniqueWithoutCheckedInput | Prisma.CheckedUsersUpdateWithWhereUniqueWithoutCheckedInput[]
  updateMany?: Prisma.CheckedUsersUpdateManyWithWhereWithoutCheckedInput | Prisma.CheckedUsersUpdateManyWithWhereWithoutCheckedInput[]
  deleteMany?: Prisma.CheckedUsersScalarWhereInput | Prisma.CheckedUsersScalarWhereInput[]
}

export type CheckedUsersUncheckedUpdateManyWithoutWasCheckedNestedInput = {
  create?: Prisma.XOR<Prisma.CheckedUsersCreateWithoutWasCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput> | Prisma.CheckedUsersCreateWithoutWasCheckedInput[] | Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput[]
  connectOrCreate?: Prisma.CheckedUsersCreateOrConnectWithoutWasCheckedInput | Prisma.CheckedUsersCreateOrConnectWithoutWasCheckedInput[]
  upsert?: Prisma.CheckedUsersUpsertWithWhereUniqueWithoutWasCheckedInput | Prisma.CheckedUsersUpsertWithWhereUniqueWithoutWasCheckedInput[]
  createMany?: Prisma.CheckedUsersCreateManyWasCheckedInputEnvelope
  set?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  disconnect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  delete?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  connect?: Prisma.CheckedUsersWhereUniqueInput | Prisma.CheckedUsersWhereUniqueInput[]
  update?: Prisma.CheckedUsersUpdateWithWhereUniqueWithoutWasCheckedInput | Prisma.CheckedUsersUpdateWithWhereUniqueWithoutWasCheckedInput[]
  updateMany?: Prisma.CheckedUsersUpdateManyWithWhereWithoutWasCheckedInput | Prisma.CheckedUsersUpdateManyWithWhereWithoutWasCheckedInput[]
  deleteMany?: Prisma.CheckedUsersScalarWhereInput | Prisma.CheckedUsersScalarWhereInput[]
}

export type CheckedUsersCreateWithoutCheckedInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  wasChecked: Prisma.UserCreateNestedOneWithoutWasCheckedInput
}

export type CheckedUsersUncheckedCreateWithoutCheckedInput = {
  wasCheckedId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CheckedUsersCreateOrConnectWithoutCheckedInput = {
  where: Prisma.CheckedUsersWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckedUsersCreateWithoutCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput>
}

export type CheckedUsersCreateManyCheckedInputEnvelope = {
  data: Prisma.CheckedUsersCreateManyCheckedInput | Prisma.CheckedUsersCreateManyCheckedInput[]
  skipDuplicates?: boolean
}

export type CheckedUsersCreateWithoutWasCheckedInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  checked: Prisma.UserCreateNestedOneWithoutCheckedInput
}

export type CheckedUsersUncheckedCreateWithoutWasCheckedInput = {
  checkedId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CheckedUsersCreateOrConnectWithoutWasCheckedInput = {
  where: Prisma.CheckedUsersWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckedUsersCreateWithoutWasCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput>
}

export type CheckedUsersCreateManyWasCheckedInputEnvelope = {
  data: Prisma.CheckedUsersCreateManyWasCheckedInput | Prisma.CheckedUsersCreateManyWasCheckedInput[]
  skipDuplicates?: boolean
}

export type CheckedUsersUpsertWithWhereUniqueWithoutCheckedInput = {
  where: Prisma.CheckedUsersWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckedUsersUpdateWithoutCheckedInput, Prisma.CheckedUsersUncheckedUpdateWithoutCheckedInput>
  create: Prisma.XOR<Prisma.CheckedUsersCreateWithoutCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutCheckedInput>
}

export type CheckedUsersUpdateWithWhereUniqueWithoutCheckedInput = {
  where: Prisma.CheckedUsersWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckedUsersUpdateWithoutCheckedInput, Prisma.CheckedUsersUncheckedUpdateWithoutCheckedInput>
}

export type CheckedUsersUpdateManyWithWhereWithoutCheckedInput = {
  where: Prisma.CheckedUsersScalarWhereInput
  data: Prisma.XOR<Prisma.CheckedUsersUpdateManyMutationInput, Prisma.CheckedUsersUncheckedUpdateManyWithoutCheckedInput>
}

export type CheckedUsersScalarWhereInput = {
  AND?: Prisma.CheckedUsersScalarWhereInput | Prisma.CheckedUsersScalarWhereInput[]
  OR?: Prisma.CheckedUsersScalarWhereInput[]
  NOT?: Prisma.CheckedUsersScalarWhereInput | Prisma.CheckedUsersScalarWhereInput[]
  checkedId?: Prisma.StringFilter<"CheckedUsers"> | string
  wasCheckedId?: Prisma.StringFilter<"CheckedUsers"> | string
  createdAt?: Prisma.DateTimeFilter<"CheckedUsers"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CheckedUsers"> | Date | string
}

export type CheckedUsersUpsertWithWhereUniqueWithoutWasCheckedInput = {
  where: Prisma.CheckedUsersWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckedUsersUpdateWithoutWasCheckedInput, Prisma.CheckedUsersUncheckedUpdateWithoutWasCheckedInput>
  create: Prisma.XOR<Prisma.CheckedUsersCreateWithoutWasCheckedInput, Prisma.CheckedUsersUncheckedCreateWithoutWasCheckedInput>
}

export type CheckedUsersUpdateWithWhereUniqueWithoutWasCheckedInput = {
  where: Prisma.CheckedUsersWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckedUsersUpdateWithoutWasCheckedInput, Prisma.CheckedUsersUncheckedUpdateWithoutWasCheckedInput>
}

export type CheckedUsersUpdateManyWithWhereWithoutWasCheckedInput = {
  where: Prisma.CheckedUsersScalarWhereInput
  data: Prisma.XOR<Prisma.CheckedUsersUpdateManyMutationInput, Prisma.CheckedUsersUncheckedUpdateManyWithoutWasCheckedInput>
}

export type CheckedUsersCreateManyCheckedInput = {
  wasCheckedId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CheckedUsersCreateManyWasCheckedInput = {
  checkedId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CheckedUsersUpdateWithoutCheckedInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  wasChecked?: Prisma.UserUpdateOneRequiredWithoutWasCheckedNestedInput
}

export type CheckedUsersUncheckedUpdateWithoutCheckedInput = {
  wasCheckedId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckedUsersUncheckedUpdateManyWithoutCheckedInput = {
  wasCheckedId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckedUsersUpdateWithoutWasCheckedInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  checked?: Prisma.UserUpdateOneRequiredWithoutCheckedNestedInput
}

export type CheckedUsersUncheckedUpdateWithoutWasCheckedInput = {
  checkedId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CheckedUsersUncheckedUpdateManyWithoutWasCheckedInput = {
  checkedId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CheckedUsersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  checkedId?: boolean
  wasCheckedId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  checked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  wasChecked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkedUsers"]>

export type CheckedUsersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  checkedId?: boolean
  wasCheckedId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  checked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  wasChecked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkedUsers"]>

export type CheckedUsersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  checkedId?: boolean
  wasCheckedId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  checked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  wasChecked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkedUsers"]>

export type CheckedUsersSelectScalar = {
  checkedId?: boolean
  wasCheckedId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CheckedUsersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"checkedId" | "wasCheckedId" | "createdAt" | "updatedAt", ExtArgs["result"]["checkedUsers"]>
export type CheckedUsersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  checked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  wasChecked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CheckedUsersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  checked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  wasChecked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type CheckedUsersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  checked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  wasChecked?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $CheckedUsersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CheckedUsers"
  objects: {
    checked: Prisma.$UserPayload<ExtArgs>
    wasChecked: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    checkedId: string
    wasCheckedId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["checkedUsers"]>
  composites: {}
}

export type CheckedUsersGetPayload<S extends boolean | null | undefined | CheckedUsersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload, S>

export type CheckedUsersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CheckedUsersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CheckedUsersCountAggregateInputType | true
  }

export interface CheckedUsersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CheckedUsers'], meta: { name: 'CheckedUsers' } }
  /**
   * Find zero or one CheckedUsers that matches the filter.
   * @param {CheckedUsersFindUniqueArgs} args - Arguments to find a CheckedUsers
   * @example
   * // Get one CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CheckedUsersFindUniqueArgs>(args: Prisma.SelectSubset<T, CheckedUsersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CheckedUsersClient<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CheckedUsers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CheckedUsersFindUniqueOrThrowArgs} args - Arguments to find a CheckedUsers
   * @example
   * // Get one CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CheckedUsersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CheckedUsersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckedUsersClient<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CheckedUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckedUsersFindFirstArgs} args - Arguments to find a CheckedUsers
   * @example
   * // Get one CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CheckedUsersFindFirstArgs>(args?: Prisma.SelectSubset<T, CheckedUsersFindFirstArgs<ExtArgs>>): Prisma.Prisma__CheckedUsersClient<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CheckedUsers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckedUsersFindFirstOrThrowArgs} args - Arguments to find a CheckedUsers
   * @example
   * // Get one CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CheckedUsersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CheckedUsersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckedUsersClient<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CheckedUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckedUsersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.findMany()
   * 
   * // Get first 10 CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.findMany({ take: 10 })
   * 
   * // Only select the `checkedId`
   * const checkedUsersWithCheckedIdOnly = await prisma.checkedUsers.findMany({ select: { checkedId: true } })
   * 
   */
  findMany<T extends CheckedUsersFindManyArgs>(args?: Prisma.SelectSubset<T, CheckedUsersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CheckedUsers.
   * @param {CheckedUsersCreateArgs} args - Arguments to create a CheckedUsers.
   * @example
   * // Create one CheckedUsers
   * const CheckedUsers = await prisma.checkedUsers.create({
   *   data: {
   *     // ... data to create a CheckedUsers
   *   }
   * })
   * 
   */
  create<T extends CheckedUsersCreateArgs>(args: Prisma.SelectSubset<T, CheckedUsersCreateArgs<ExtArgs>>): Prisma.Prisma__CheckedUsersClient<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CheckedUsers.
   * @param {CheckedUsersCreateManyArgs} args - Arguments to create many CheckedUsers.
   * @example
   * // Create many CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CheckedUsersCreateManyArgs>(args?: Prisma.SelectSubset<T, CheckedUsersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CheckedUsers and returns the data saved in the database.
   * @param {CheckedUsersCreateManyAndReturnArgs} args - Arguments to create many CheckedUsers.
   * @example
   * // Create many CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CheckedUsers and only return the `checkedId`
   * const checkedUsersWithCheckedIdOnly = await prisma.checkedUsers.createManyAndReturn({
   *   select: { checkedId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CheckedUsersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CheckedUsersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CheckedUsers.
   * @param {CheckedUsersDeleteArgs} args - Arguments to delete one CheckedUsers.
   * @example
   * // Delete one CheckedUsers
   * const CheckedUsers = await prisma.checkedUsers.delete({
   *   where: {
   *     // ... filter to delete one CheckedUsers
   *   }
   * })
   * 
   */
  delete<T extends CheckedUsersDeleteArgs>(args: Prisma.SelectSubset<T, CheckedUsersDeleteArgs<ExtArgs>>): Prisma.Prisma__CheckedUsersClient<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CheckedUsers.
   * @param {CheckedUsersUpdateArgs} args - Arguments to update one CheckedUsers.
   * @example
   * // Update one CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CheckedUsersUpdateArgs>(args: Prisma.SelectSubset<T, CheckedUsersUpdateArgs<ExtArgs>>): Prisma.Prisma__CheckedUsersClient<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CheckedUsers.
   * @param {CheckedUsersDeleteManyArgs} args - Arguments to filter CheckedUsers to delete.
   * @example
   * // Delete a few CheckedUsers
   * const { count } = await prisma.checkedUsers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CheckedUsersDeleteManyArgs>(args?: Prisma.SelectSubset<T, CheckedUsersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CheckedUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckedUsersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CheckedUsersUpdateManyArgs>(args: Prisma.SelectSubset<T, CheckedUsersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CheckedUsers and returns the data updated in the database.
   * @param {CheckedUsersUpdateManyAndReturnArgs} args - Arguments to update many CheckedUsers.
   * @example
   * // Update many CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CheckedUsers and only return the `checkedId`
   * const checkedUsersWithCheckedIdOnly = await prisma.checkedUsers.updateManyAndReturn({
   *   select: { checkedId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CheckedUsersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CheckedUsersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CheckedUsers.
   * @param {CheckedUsersUpsertArgs} args - Arguments to update or create a CheckedUsers.
   * @example
   * // Update or create a CheckedUsers
   * const checkedUsers = await prisma.checkedUsers.upsert({
   *   create: {
   *     // ... data to create a CheckedUsers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CheckedUsers we want to update
   *   }
   * })
   */
  upsert<T extends CheckedUsersUpsertArgs>(args: Prisma.SelectSubset<T, CheckedUsersUpsertArgs<ExtArgs>>): Prisma.Prisma__CheckedUsersClient<runtime.Types.Result.GetResult<Prisma.$CheckedUsersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CheckedUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckedUsersCountArgs} args - Arguments to filter CheckedUsers to count.
   * @example
   * // Count the number of CheckedUsers
   * const count = await prisma.checkedUsers.count({
   *   where: {
   *     // ... the filter for the CheckedUsers we want to count
   *   }
   * })
  **/
  count<T extends CheckedUsersCountArgs>(
    args?: Prisma.Subset<T, CheckedUsersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CheckedUsersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CheckedUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckedUsersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CheckedUsersAggregateArgs>(args: Prisma.Subset<T, CheckedUsersAggregateArgs>): Prisma.PrismaPromise<GetCheckedUsersAggregateType<T>>

  /**
   * Group by CheckedUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckedUsersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CheckedUsersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CheckedUsersGroupByArgs['orderBy'] }
      : { orderBy?: CheckedUsersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CheckedUsersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCheckedUsersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CheckedUsers model
 */
readonly fields: CheckedUsersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CheckedUsers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CheckedUsersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  checked<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  wasChecked<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CheckedUsers model
 */
export interface CheckedUsersFieldRefs {
  readonly checkedId: Prisma.FieldRef<"CheckedUsers", 'String'>
  readonly wasCheckedId: Prisma.FieldRef<"CheckedUsers", 'String'>
  readonly createdAt: Prisma.FieldRef<"CheckedUsers", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CheckedUsers", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CheckedUsers findUnique
 */
export type CheckedUsersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * Filter, which CheckedUsers to fetch.
   */
  where: Prisma.CheckedUsersWhereUniqueInput
}

/**
 * CheckedUsers findUniqueOrThrow
 */
export type CheckedUsersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * Filter, which CheckedUsers to fetch.
   */
  where: Prisma.CheckedUsersWhereUniqueInput
}

/**
 * CheckedUsers findFirst
 */
export type CheckedUsersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * Filter, which CheckedUsers to fetch.
   */
  where?: Prisma.CheckedUsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckedUsers to fetch.
   */
  orderBy?: Prisma.CheckedUsersOrderByWithRelationInput | Prisma.CheckedUsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CheckedUsers.
   */
  cursor?: Prisma.CheckedUsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckedUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckedUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CheckedUsers.
   */
  distinct?: Prisma.CheckedUsersScalarFieldEnum | Prisma.CheckedUsersScalarFieldEnum[]
}

/**
 * CheckedUsers findFirstOrThrow
 */
export type CheckedUsersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * Filter, which CheckedUsers to fetch.
   */
  where?: Prisma.CheckedUsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckedUsers to fetch.
   */
  orderBy?: Prisma.CheckedUsersOrderByWithRelationInput | Prisma.CheckedUsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CheckedUsers.
   */
  cursor?: Prisma.CheckedUsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckedUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckedUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CheckedUsers.
   */
  distinct?: Prisma.CheckedUsersScalarFieldEnum | Prisma.CheckedUsersScalarFieldEnum[]
}

/**
 * CheckedUsers findMany
 */
export type CheckedUsersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * Filter, which CheckedUsers to fetch.
   */
  where?: Prisma.CheckedUsersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CheckedUsers to fetch.
   */
  orderBy?: Prisma.CheckedUsersOrderByWithRelationInput | Prisma.CheckedUsersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CheckedUsers.
   */
  cursor?: Prisma.CheckedUsersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CheckedUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CheckedUsers.
   */
  skip?: number
  distinct?: Prisma.CheckedUsersScalarFieldEnum | Prisma.CheckedUsersScalarFieldEnum[]
}

/**
 * CheckedUsers create
 */
export type CheckedUsersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * The data needed to create a CheckedUsers.
   */
  data: Prisma.XOR<Prisma.CheckedUsersCreateInput, Prisma.CheckedUsersUncheckedCreateInput>
}

/**
 * CheckedUsers createMany
 */
export type CheckedUsersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CheckedUsers.
   */
  data: Prisma.CheckedUsersCreateManyInput | Prisma.CheckedUsersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CheckedUsers createManyAndReturn
 */
export type CheckedUsersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * The data used to create many CheckedUsers.
   */
  data: Prisma.CheckedUsersCreateManyInput | Prisma.CheckedUsersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CheckedUsers update
 */
export type CheckedUsersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * The data needed to update a CheckedUsers.
   */
  data: Prisma.XOR<Prisma.CheckedUsersUpdateInput, Prisma.CheckedUsersUncheckedUpdateInput>
  /**
   * Choose, which CheckedUsers to update.
   */
  where: Prisma.CheckedUsersWhereUniqueInput
}

/**
 * CheckedUsers updateMany
 */
export type CheckedUsersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CheckedUsers.
   */
  data: Prisma.XOR<Prisma.CheckedUsersUpdateManyMutationInput, Prisma.CheckedUsersUncheckedUpdateManyInput>
  /**
   * Filter which CheckedUsers to update
   */
  where?: Prisma.CheckedUsersWhereInput
  /**
   * Limit how many CheckedUsers to update.
   */
  limit?: number
}

/**
 * CheckedUsers updateManyAndReturn
 */
export type CheckedUsersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * The data used to update CheckedUsers.
   */
  data: Prisma.XOR<Prisma.CheckedUsersUpdateManyMutationInput, Prisma.CheckedUsersUncheckedUpdateManyInput>
  /**
   * Filter which CheckedUsers to update
   */
  where?: Prisma.CheckedUsersWhereInput
  /**
   * Limit how many CheckedUsers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CheckedUsers upsert
 */
export type CheckedUsersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * The filter to search for the CheckedUsers to update in case it exists.
   */
  where: Prisma.CheckedUsersWhereUniqueInput
  /**
   * In case the CheckedUsers found by the `where` argument doesn't exist, create a new CheckedUsers with this data.
   */
  create: Prisma.XOR<Prisma.CheckedUsersCreateInput, Prisma.CheckedUsersUncheckedCreateInput>
  /**
   * In case the CheckedUsers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CheckedUsersUpdateInput, Prisma.CheckedUsersUncheckedUpdateInput>
}

/**
 * CheckedUsers delete
 */
export type CheckedUsersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
  /**
   * Filter which CheckedUsers to delete.
   */
  where: Prisma.CheckedUsersWhereUniqueInput
}

/**
 * CheckedUsers deleteMany
 */
export type CheckedUsersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CheckedUsers to delete
   */
  where?: Prisma.CheckedUsersWhereInput
  /**
   * Limit how many CheckedUsers to delete.
   */
  limit?: number
}

/**
 * CheckedUsers without action
 */
export type CheckedUsersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckedUsers
   */
  select?: Prisma.CheckedUsersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CheckedUsers
   */
  omit?: Prisma.CheckedUsersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckedUsersInclude<ExtArgs> | null
}
