
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Picture` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Picture
 * 
 */
export type PictureModel = runtime.Types.Result.DefaultSelection<Prisma.$PicturePayload>

export type AggregatePicture = {
  _count: PictureCountAggregateOutputType | null
  _avg: PictureAvgAggregateOutputType | null
  _sum: PictureSumAggregateOutputType | null
  _min: PictureMinAggregateOutputType | null
  _max: PictureMaxAggregateOutputType | null
}

export type PictureAvgAggregateOutputType = {
  order: number | null
}

export type PictureSumAggregateOutputType = {
  order: number | null
}

export type PictureMinAggregateOutputType = {
  id: string | null
  userId: string | null
  order: number | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PictureMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  order: number | null
  name: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PictureCountAggregateOutputType = {
  id: number
  userId: number
  order: number
  name: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PictureAvgAggregateInputType = {
  order?: true
}

export type PictureSumAggregateInputType = {
  order?: true
}

export type PictureMinAggregateInputType = {
  id?: true
  userId?: true
  order?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type PictureMaxAggregateInputType = {
  id?: true
  userId?: true
  order?: true
  name?: true
  createdAt?: true
  updatedAt?: true
}

export type PictureCountAggregateInputType = {
  id?: true
  userId?: true
  order?: true
  name?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PictureAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Picture to aggregate.
   */
  where?: Prisma.PictureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pictures to fetch.
   */
  orderBy?: Prisma.PictureOrderByWithRelationInput | Prisma.PictureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PictureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pictures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pictures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Pictures
  **/
  _count?: true | PictureCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PictureAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PictureSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PictureMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PictureMaxAggregateInputType
}

export type GetPictureAggregateType<T extends PictureAggregateArgs> = {
      [P in keyof T & keyof AggregatePicture]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePicture[P]>
    : Prisma.GetScalarType<T[P], AggregatePicture[P]>
}




export type PictureGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PictureWhereInput
  orderBy?: Prisma.PictureOrderByWithAggregationInput | Prisma.PictureOrderByWithAggregationInput[]
  by: Prisma.PictureScalarFieldEnum[] | Prisma.PictureScalarFieldEnum
  having?: Prisma.PictureScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PictureCountAggregateInputType | true
  _avg?: PictureAvgAggregateInputType
  _sum?: PictureSumAggregateInputType
  _min?: PictureMinAggregateInputType
  _max?: PictureMaxAggregateInputType
}

export type PictureGroupByOutputType = {
  id: string
  userId: string
  order: number
  name: string
  createdAt: Date
  updatedAt: Date
  _count: PictureCountAggregateOutputType | null
  _avg: PictureAvgAggregateOutputType | null
  _sum: PictureSumAggregateOutputType | null
  _min: PictureMinAggregateOutputType | null
  _max: PictureMaxAggregateOutputType | null
}

type GetPictureGroupByPayload<T extends PictureGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PictureGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PictureGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PictureGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PictureGroupByOutputType[P]>
      }
    >
  >



export type PictureWhereInput = {
  AND?: Prisma.PictureWhereInput | Prisma.PictureWhereInput[]
  OR?: Prisma.PictureWhereInput[]
  NOT?: Prisma.PictureWhereInput | Prisma.PictureWhereInput[]
  id?: Prisma.StringFilter<"Picture"> | string
  userId?: Prisma.StringFilter<"Picture"> | string
  order?: Prisma.IntFilter<"Picture"> | number
  name?: Prisma.StringFilter<"Picture"> | string
  createdAt?: Prisma.DateTimeFilter<"Picture"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Picture"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PictureOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type PictureWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PictureWhereInput | Prisma.PictureWhereInput[]
  OR?: Prisma.PictureWhereInput[]
  NOT?: Prisma.PictureWhereInput | Prisma.PictureWhereInput[]
  userId?: Prisma.StringFilter<"Picture"> | string
  order?: Prisma.IntFilter<"Picture"> | number
  name?: Prisma.StringFilter<"Picture"> | string
  createdAt?: Prisma.DateTimeFilter<"Picture"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Picture"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type PictureOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PictureCountOrderByAggregateInput
  _avg?: Prisma.PictureAvgOrderByAggregateInput
  _max?: Prisma.PictureMaxOrderByAggregateInput
  _min?: Prisma.PictureMinOrderByAggregateInput
  _sum?: Prisma.PictureSumOrderByAggregateInput
}

export type PictureScalarWhereWithAggregatesInput = {
  AND?: Prisma.PictureScalarWhereWithAggregatesInput | Prisma.PictureScalarWhereWithAggregatesInput[]
  OR?: Prisma.PictureScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PictureScalarWhereWithAggregatesInput | Prisma.PictureScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Picture"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Picture"> | string
  order?: Prisma.IntWithAggregatesFilter<"Picture"> | number
  name?: Prisma.StringWithAggregatesFilter<"Picture"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Picture"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Picture"> | Date | string
}

export type PictureCreateInput = {
  id?: string
  order: number
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPicturesInput
}

export type PictureUncheckedCreateInput = {
  id?: string
  userId: string
  order: number
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PictureUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPicturesNestedInput
}

export type PictureUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PictureCreateManyInput = {
  id?: string
  userId: string
  order: number
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PictureUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PictureUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PictureListRelationFilter = {
  every?: Prisma.PictureWhereInput
  some?: Prisma.PictureWhereInput
  none?: Prisma.PictureWhereInput
}

export type PictureOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PictureCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PictureAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type PictureMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PictureMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PictureSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type PictureCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PictureCreateWithoutUserInput, Prisma.PictureUncheckedCreateWithoutUserInput> | Prisma.PictureCreateWithoutUserInput[] | Prisma.PictureUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PictureCreateOrConnectWithoutUserInput | Prisma.PictureCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PictureCreateManyUserInputEnvelope
  connect?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
}

export type PictureUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PictureCreateWithoutUserInput, Prisma.PictureUncheckedCreateWithoutUserInput> | Prisma.PictureCreateWithoutUserInput[] | Prisma.PictureUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PictureCreateOrConnectWithoutUserInput | Prisma.PictureCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PictureCreateManyUserInputEnvelope
  connect?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
}

export type PictureUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PictureCreateWithoutUserInput, Prisma.PictureUncheckedCreateWithoutUserInput> | Prisma.PictureCreateWithoutUserInput[] | Prisma.PictureUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PictureCreateOrConnectWithoutUserInput | Prisma.PictureCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PictureUpsertWithWhereUniqueWithoutUserInput | Prisma.PictureUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PictureCreateManyUserInputEnvelope
  set?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
  disconnect?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
  delete?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
  connect?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
  update?: Prisma.PictureUpdateWithWhereUniqueWithoutUserInput | Prisma.PictureUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PictureUpdateManyWithWhereWithoutUserInput | Prisma.PictureUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PictureScalarWhereInput | Prisma.PictureScalarWhereInput[]
}

export type PictureUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PictureCreateWithoutUserInput, Prisma.PictureUncheckedCreateWithoutUserInput> | Prisma.PictureCreateWithoutUserInput[] | Prisma.PictureUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PictureCreateOrConnectWithoutUserInput | Prisma.PictureCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PictureUpsertWithWhereUniqueWithoutUserInput | Prisma.PictureUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PictureCreateManyUserInputEnvelope
  set?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
  disconnect?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
  delete?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
  connect?: Prisma.PictureWhereUniqueInput | Prisma.PictureWhereUniqueInput[]
  update?: Prisma.PictureUpdateWithWhereUniqueWithoutUserInput | Prisma.PictureUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PictureUpdateManyWithWhereWithoutUserInput | Prisma.PictureUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PictureScalarWhereInput | Prisma.PictureScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PictureCreateWithoutUserInput = {
  id?: string
  order: number
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PictureUncheckedCreateWithoutUserInput = {
  id?: string
  order: number
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PictureCreateOrConnectWithoutUserInput = {
  where: Prisma.PictureWhereUniqueInput
  create: Prisma.XOR<Prisma.PictureCreateWithoutUserInput, Prisma.PictureUncheckedCreateWithoutUserInput>
}

export type PictureCreateManyUserInputEnvelope = {
  data: Prisma.PictureCreateManyUserInput | Prisma.PictureCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PictureUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PictureWhereUniqueInput
  update: Prisma.XOR<Prisma.PictureUpdateWithoutUserInput, Prisma.PictureUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PictureCreateWithoutUserInput, Prisma.PictureUncheckedCreateWithoutUserInput>
}

export type PictureUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PictureWhereUniqueInput
  data: Prisma.XOR<Prisma.PictureUpdateWithoutUserInput, Prisma.PictureUncheckedUpdateWithoutUserInput>
}

export type PictureUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PictureScalarWhereInput
  data: Prisma.XOR<Prisma.PictureUpdateManyMutationInput, Prisma.PictureUncheckedUpdateManyWithoutUserInput>
}

export type PictureScalarWhereInput = {
  AND?: Prisma.PictureScalarWhereInput | Prisma.PictureScalarWhereInput[]
  OR?: Prisma.PictureScalarWhereInput[]
  NOT?: Prisma.PictureScalarWhereInput | Prisma.PictureScalarWhereInput[]
  id?: Prisma.StringFilter<"Picture"> | string
  userId?: Prisma.StringFilter<"Picture"> | string
  order?: Prisma.IntFilter<"Picture"> | number
  name?: Prisma.StringFilter<"Picture"> | string
  createdAt?: Prisma.DateTimeFilter<"Picture"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Picture"> | Date | string
}

export type PictureCreateManyUserInput = {
  id?: string
  order: number
  name: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PictureUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PictureUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PictureUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PictureSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  order?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["picture"]>

export type PictureSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  order?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["picture"]>

export type PictureSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  order?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["picture"]>

export type PictureSelectScalar = {
  id?: boolean
  userId?: boolean
  order?: boolean
  name?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PictureOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "order" | "name" | "createdAt" | "updatedAt", ExtArgs["result"]["picture"]>
export type PictureInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PictureIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PictureIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PicturePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Picture"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    order: number
    name: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["picture"]>
  composites: {}
}

export type PictureGetPayload<S extends boolean | null | undefined | PictureDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PicturePayload, S>

export type PictureCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PictureFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PictureCountAggregateInputType | true
  }

export interface PictureDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Picture'], meta: { name: 'Picture' } }
  /**
   * Find zero or one Picture that matches the filter.
   * @param {PictureFindUniqueArgs} args - Arguments to find a Picture
   * @example
   * // Get one Picture
   * const picture = await prisma.picture.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PictureFindUniqueArgs>(args: Prisma.SelectSubset<T, PictureFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PictureClient<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Picture that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PictureFindUniqueOrThrowArgs} args - Arguments to find a Picture
   * @example
   * // Get one Picture
   * const picture = await prisma.picture.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PictureFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PictureFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PictureClient<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Picture that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PictureFindFirstArgs} args - Arguments to find a Picture
   * @example
   * // Get one Picture
   * const picture = await prisma.picture.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PictureFindFirstArgs>(args?: Prisma.SelectSubset<T, PictureFindFirstArgs<ExtArgs>>): Prisma.Prisma__PictureClient<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Picture that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PictureFindFirstOrThrowArgs} args - Arguments to find a Picture
   * @example
   * // Get one Picture
   * const picture = await prisma.picture.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PictureFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PictureFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PictureClient<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Pictures that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PictureFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Pictures
   * const pictures = await prisma.picture.findMany()
   * 
   * // Get first 10 Pictures
   * const pictures = await prisma.picture.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pictureWithIdOnly = await prisma.picture.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PictureFindManyArgs>(args?: Prisma.SelectSubset<T, PictureFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Picture.
   * @param {PictureCreateArgs} args - Arguments to create a Picture.
   * @example
   * // Create one Picture
   * const Picture = await prisma.picture.create({
   *   data: {
   *     // ... data to create a Picture
   *   }
   * })
   * 
   */
  create<T extends PictureCreateArgs>(args: Prisma.SelectSubset<T, PictureCreateArgs<ExtArgs>>): Prisma.Prisma__PictureClient<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Pictures.
   * @param {PictureCreateManyArgs} args - Arguments to create many Pictures.
   * @example
   * // Create many Pictures
   * const picture = await prisma.picture.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PictureCreateManyArgs>(args?: Prisma.SelectSubset<T, PictureCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Pictures and returns the data saved in the database.
   * @param {PictureCreateManyAndReturnArgs} args - Arguments to create many Pictures.
   * @example
   * // Create many Pictures
   * const picture = await prisma.picture.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Pictures and only return the `id`
   * const pictureWithIdOnly = await prisma.picture.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PictureCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PictureCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Picture.
   * @param {PictureDeleteArgs} args - Arguments to delete one Picture.
   * @example
   * // Delete one Picture
   * const Picture = await prisma.picture.delete({
   *   where: {
   *     // ... filter to delete one Picture
   *   }
   * })
   * 
   */
  delete<T extends PictureDeleteArgs>(args: Prisma.SelectSubset<T, PictureDeleteArgs<ExtArgs>>): Prisma.Prisma__PictureClient<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Picture.
   * @param {PictureUpdateArgs} args - Arguments to update one Picture.
   * @example
   * // Update one Picture
   * const picture = await prisma.picture.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PictureUpdateArgs>(args: Prisma.SelectSubset<T, PictureUpdateArgs<ExtArgs>>): Prisma.Prisma__PictureClient<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Pictures.
   * @param {PictureDeleteManyArgs} args - Arguments to filter Pictures to delete.
   * @example
   * // Delete a few Pictures
   * const { count } = await prisma.picture.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PictureDeleteManyArgs>(args?: Prisma.SelectSubset<T, PictureDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pictures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PictureUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Pictures
   * const picture = await prisma.picture.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PictureUpdateManyArgs>(args: Prisma.SelectSubset<T, PictureUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pictures and returns the data updated in the database.
   * @param {PictureUpdateManyAndReturnArgs} args - Arguments to update many Pictures.
   * @example
   * // Update many Pictures
   * const picture = await prisma.picture.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Pictures and only return the `id`
   * const pictureWithIdOnly = await prisma.picture.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PictureUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PictureUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Picture.
   * @param {PictureUpsertArgs} args - Arguments to update or create a Picture.
   * @example
   * // Update or create a Picture
   * const picture = await prisma.picture.upsert({
   *   create: {
   *     // ... data to create a Picture
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Picture we want to update
   *   }
   * })
   */
  upsert<T extends PictureUpsertArgs>(args: Prisma.SelectSubset<T, PictureUpsertArgs<ExtArgs>>): Prisma.Prisma__PictureClient<runtime.Types.Result.GetResult<Prisma.$PicturePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Pictures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PictureCountArgs} args - Arguments to filter Pictures to count.
   * @example
   * // Count the number of Pictures
   * const count = await prisma.picture.count({
   *   where: {
   *     // ... the filter for the Pictures we want to count
   *   }
   * })
  **/
  count<T extends PictureCountArgs>(
    args?: Prisma.Subset<T, PictureCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PictureCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Picture.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PictureAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PictureAggregateArgs>(args: Prisma.Subset<T, PictureAggregateArgs>): Prisma.PrismaPromise<GetPictureAggregateType<T>>

  /**
   * Group by Picture.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PictureGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PictureGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PictureGroupByArgs['orderBy'] }
      : { orderBy?: PictureGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PictureGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPictureGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Picture model
 */
readonly fields: PictureFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Picture.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PictureClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Picture model
 */
export interface PictureFieldRefs {
  readonly id: Prisma.FieldRef<"Picture", 'String'>
  readonly userId: Prisma.FieldRef<"Picture", 'String'>
  readonly order: Prisma.FieldRef<"Picture", 'Int'>
  readonly name: Prisma.FieldRef<"Picture", 'String'>
  readonly createdAt: Prisma.FieldRef<"Picture", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Picture", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Picture findUnique
 */
export type PictureFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * Filter, which Picture to fetch.
   */
  where: Prisma.PictureWhereUniqueInput
}

/**
 * Picture findUniqueOrThrow
 */
export type PictureFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * Filter, which Picture to fetch.
   */
  where: Prisma.PictureWhereUniqueInput
}

/**
 * Picture findFirst
 */
export type PictureFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * Filter, which Picture to fetch.
   */
  where?: Prisma.PictureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pictures to fetch.
   */
  orderBy?: Prisma.PictureOrderByWithRelationInput | Prisma.PictureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pictures.
   */
  cursor?: Prisma.PictureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pictures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pictures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pictures.
   */
  distinct?: Prisma.PictureScalarFieldEnum | Prisma.PictureScalarFieldEnum[]
}

/**
 * Picture findFirstOrThrow
 */
export type PictureFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * Filter, which Picture to fetch.
   */
  where?: Prisma.PictureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pictures to fetch.
   */
  orderBy?: Prisma.PictureOrderByWithRelationInput | Prisma.PictureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pictures.
   */
  cursor?: Prisma.PictureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pictures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pictures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pictures.
   */
  distinct?: Prisma.PictureScalarFieldEnum | Prisma.PictureScalarFieldEnum[]
}

/**
 * Picture findMany
 */
export type PictureFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * Filter, which Pictures to fetch.
   */
  where?: Prisma.PictureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pictures to fetch.
   */
  orderBy?: Prisma.PictureOrderByWithRelationInput | Prisma.PictureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Pictures.
   */
  cursor?: Prisma.PictureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pictures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pictures.
   */
  skip?: number
  distinct?: Prisma.PictureScalarFieldEnum | Prisma.PictureScalarFieldEnum[]
}

/**
 * Picture create
 */
export type PictureCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * The data needed to create a Picture.
   */
  data: Prisma.XOR<Prisma.PictureCreateInput, Prisma.PictureUncheckedCreateInput>
}

/**
 * Picture createMany
 */
export type PictureCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Pictures.
   */
  data: Prisma.PictureCreateManyInput | Prisma.PictureCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Picture createManyAndReturn
 */
export type PictureCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * The data used to create many Pictures.
   */
  data: Prisma.PictureCreateManyInput | Prisma.PictureCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Picture update
 */
export type PictureUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * The data needed to update a Picture.
   */
  data: Prisma.XOR<Prisma.PictureUpdateInput, Prisma.PictureUncheckedUpdateInput>
  /**
   * Choose, which Picture to update.
   */
  where: Prisma.PictureWhereUniqueInput
}

/**
 * Picture updateMany
 */
export type PictureUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Pictures.
   */
  data: Prisma.XOR<Prisma.PictureUpdateManyMutationInput, Prisma.PictureUncheckedUpdateManyInput>
  /**
   * Filter which Pictures to update
   */
  where?: Prisma.PictureWhereInput
  /**
   * Limit how many Pictures to update.
   */
  limit?: number
}

/**
 * Picture updateManyAndReturn
 */
export type PictureUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * The data used to update Pictures.
   */
  data: Prisma.XOR<Prisma.PictureUpdateManyMutationInput, Prisma.PictureUncheckedUpdateManyInput>
  /**
   * Filter which Pictures to update
   */
  where?: Prisma.PictureWhereInput
  /**
   * Limit how many Pictures to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Picture upsert
 */
export type PictureUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * The filter to search for the Picture to update in case it exists.
   */
  where: Prisma.PictureWhereUniqueInput
  /**
   * In case the Picture found by the `where` argument doesn't exist, create a new Picture with this data.
   */
  create: Prisma.XOR<Prisma.PictureCreateInput, Prisma.PictureUncheckedCreateInput>
  /**
   * In case the Picture was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PictureUpdateInput, Prisma.PictureUncheckedUpdateInput>
}

/**
 * Picture delete
 */
export type PictureDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
  /**
   * Filter which Picture to delete.
   */
  where: Prisma.PictureWhereUniqueInput
}

/**
 * Picture deleteMany
 */
export type PictureDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pictures to delete
   */
  where?: Prisma.PictureWhereInput
  /**
   * Limit how many Pictures to delete.
   */
  limit?: number
}

/**
 * Picture without action
 */
export type PictureDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Picture
   */
  select?: Prisma.PictureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Picture
   */
  omit?: Prisma.PictureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PictureInclude<ExtArgs> | null
}
