
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UsersOnChats` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UsersOnChats
 * 
 */
export type UsersOnChatsModel = runtime.Types.Result.DefaultSelection<Prisma.$UsersOnChatsPayload>

export type AggregateUsersOnChats = {
  _count: UsersOnChatsCountAggregateOutputType | null
  _avg: UsersOnChatsAvgAggregateOutputType | null
  _sum: UsersOnChatsSumAggregateOutputType | null
  _min: UsersOnChatsMinAggregateOutputType | null
  _max: UsersOnChatsMaxAggregateOutputType | null
}

export type UsersOnChatsAvgAggregateOutputType = {
  newMessagesCount: number | null
}

export type UsersOnChatsSumAggregateOutputType = {
  newMessagesCount: number | null
}

export type UsersOnChatsMinAggregateOutputType = {
  chatId: string | null
  userId: string | null
  newMessagesCount: number | null
  createdAt: Date | null
  lastSeenAt: Date | null
}

export type UsersOnChatsMaxAggregateOutputType = {
  chatId: string | null
  userId: string | null
  newMessagesCount: number | null
  createdAt: Date | null
  lastSeenAt: Date | null
}

export type UsersOnChatsCountAggregateOutputType = {
  chatId: number
  userId: number
  newMessagesCount: number
  createdAt: number
  lastSeenAt: number
  _all: number
}


export type UsersOnChatsAvgAggregateInputType = {
  newMessagesCount?: true
}

export type UsersOnChatsSumAggregateInputType = {
  newMessagesCount?: true
}

export type UsersOnChatsMinAggregateInputType = {
  chatId?: true
  userId?: true
  newMessagesCount?: true
  createdAt?: true
  lastSeenAt?: true
}

export type UsersOnChatsMaxAggregateInputType = {
  chatId?: true
  userId?: true
  newMessagesCount?: true
  createdAt?: true
  lastSeenAt?: true
}

export type UsersOnChatsCountAggregateInputType = {
  chatId?: true
  userId?: true
  newMessagesCount?: true
  createdAt?: true
  lastSeenAt?: true
  _all?: true
}

export type UsersOnChatsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UsersOnChats to aggregate.
   */
  where?: Prisma.UsersOnChatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UsersOnChats to fetch.
   */
  orderBy?: Prisma.UsersOnChatsOrderByWithRelationInput | Prisma.UsersOnChatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UsersOnChatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UsersOnChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UsersOnChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UsersOnChats
  **/
  _count?: true | UsersOnChatsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UsersOnChatsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UsersOnChatsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UsersOnChatsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UsersOnChatsMaxAggregateInputType
}

export type GetUsersOnChatsAggregateType<T extends UsersOnChatsAggregateArgs> = {
      [P in keyof T & keyof AggregateUsersOnChats]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsersOnChats[P]>
    : Prisma.GetScalarType<T[P], AggregateUsersOnChats[P]>
}




export type UsersOnChatsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UsersOnChatsWhereInput
  orderBy?: Prisma.UsersOnChatsOrderByWithAggregationInput | Prisma.UsersOnChatsOrderByWithAggregationInput[]
  by: Prisma.UsersOnChatsScalarFieldEnum[] | Prisma.UsersOnChatsScalarFieldEnum
  having?: Prisma.UsersOnChatsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UsersOnChatsCountAggregateInputType | true
  _avg?: UsersOnChatsAvgAggregateInputType
  _sum?: UsersOnChatsSumAggregateInputType
  _min?: UsersOnChatsMinAggregateInputType
  _max?: UsersOnChatsMaxAggregateInputType
}

export type UsersOnChatsGroupByOutputType = {
  chatId: string
  userId: string
  newMessagesCount: number
  createdAt: Date
  lastSeenAt: Date
  _count: UsersOnChatsCountAggregateOutputType | null
  _avg: UsersOnChatsAvgAggregateOutputType | null
  _sum: UsersOnChatsSumAggregateOutputType | null
  _min: UsersOnChatsMinAggregateOutputType | null
  _max: UsersOnChatsMaxAggregateOutputType | null
}

type GetUsersOnChatsGroupByPayload<T extends UsersOnChatsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsersOnChatsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UsersOnChatsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UsersOnChatsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UsersOnChatsGroupByOutputType[P]>
      }
    >
  >



export type UsersOnChatsWhereInput = {
  AND?: Prisma.UsersOnChatsWhereInput | Prisma.UsersOnChatsWhereInput[]
  OR?: Prisma.UsersOnChatsWhereInput[]
  NOT?: Prisma.UsersOnChatsWhereInput | Prisma.UsersOnChatsWhereInput[]
  chatId?: Prisma.StringFilter<"UsersOnChats"> | string
  userId?: Prisma.StringFilter<"UsersOnChats"> | string
  newMessagesCount?: Prisma.IntFilter<"UsersOnChats"> | number
  createdAt?: Prisma.DateTimeFilter<"UsersOnChats"> | Date | string
  lastSeenAt?: Prisma.DateTimeFilter<"UsersOnChats"> | Date | string
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UsersOnChatsOrderByWithRelationInput = {
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  newMessagesCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrder
  chat?: Prisma.ChatOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type UsersOnChatsWhereUniqueInput = Prisma.AtLeast<{
  userId_chatId?: Prisma.UsersOnChatsUserIdChatIdCompoundUniqueInput
  AND?: Prisma.UsersOnChatsWhereInput | Prisma.UsersOnChatsWhereInput[]
  OR?: Prisma.UsersOnChatsWhereInput[]
  NOT?: Prisma.UsersOnChatsWhereInput | Prisma.UsersOnChatsWhereInput[]
  chatId?: Prisma.StringFilter<"UsersOnChats"> | string
  userId?: Prisma.StringFilter<"UsersOnChats"> | string
  newMessagesCount?: Prisma.IntFilter<"UsersOnChats"> | number
  createdAt?: Prisma.DateTimeFilter<"UsersOnChats"> | Date | string
  lastSeenAt?: Prisma.DateTimeFilter<"UsersOnChats"> | Date | string
  chat?: Prisma.XOR<Prisma.ChatScalarRelationFilter, Prisma.ChatWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "userId_chatId">

export type UsersOnChatsOrderByWithAggregationInput = {
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  newMessagesCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrder
  _count?: Prisma.UsersOnChatsCountOrderByAggregateInput
  _avg?: Prisma.UsersOnChatsAvgOrderByAggregateInput
  _max?: Prisma.UsersOnChatsMaxOrderByAggregateInput
  _min?: Prisma.UsersOnChatsMinOrderByAggregateInput
  _sum?: Prisma.UsersOnChatsSumOrderByAggregateInput
}

export type UsersOnChatsScalarWhereWithAggregatesInput = {
  AND?: Prisma.UsersOnChatsScalarWhereWithAggregatesInput | Prisma.UsersOnChatsScalarWhereWithAggregatesInput[]
  OR?: Prisma.UsersOnChatsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UsersOnChatsScalarWhereWithAggregatesInput | Prisma.UsersOnChatsScalarWhereWithAggregatesInput[]
  chatId?: Prisma.StringWithAggregatesFilter<"UsersOnChats"> | string
  userId?: Prisma.StringWithAggregatesFilter<"UsersOnChats"> | string
  newMessagesCount?: Prisma.IntWithAggregatesFilter<"UsersOnChats"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UsersOnChats"> | Date | string
  lastSeenAt?: Prisma.DateTimeWithAggregatesFilter<"UsersOnChats"> | Date | string
}

export type UsersOnChatsCreateInput = {
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutUsersInput
  user: Prisma.UserCreateNestedOneWithoutChatsInput
}

export type UsersOnChatsUncheckedCreateInput = {
  chatId: string
  userId: string
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
}

export type UsersOnChatsUpdateInput = {
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutUsersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutChatsNestedInput
}

export type UsersOnChatsUncheckedUpdateInput = {
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsersOnChatsCreateManyInput = {
  chatId: string
  userId: string
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
}

export type UsersOnChatsUpdateManyMutationInput = {
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsersOnChatsUncheckedUpdateManyInput = {
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsersOnChatsListRelationFilter = {
  every?: Prisma.UsersOnChatsWhereInput
  some?: Prisma.UsersOnChatsWhereInput
  none?: Prisma.UsersOnChatsWhereInput
}

export type UsersOnChatsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UsersOnChatsUserIdChatIdCompoundUniqueInput = {
  userId: string
  chatId: string
}

export type UsersOnChatsCountOrderByAggregateInput = {
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  newMessagesCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrder
}

export type UsersOnChatsAvgOrderByAggregateInput = {
  newMessagesCount?: Prisma.SortOrder
}

export type UsersOnChatsMaxOrderByAggregateInput = {
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  newMessagesCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrder
}

export type UsersOnChatsMinOrderByAggregateInput = {
  chatId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  newMessagesCount?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  lastSeenAt?: Prisma.SortOrder
}

export type UsersOnChatsSumOrderByAggregateInput = {
  newMessagesCount?: Prisma.SortOrder
}

export type UsersOnChatsCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutUserInput, Prisma.UsersOnChatsUncheckedCreateWithoutUserInput> | Prisma.UsersOnChatsCreateWithoutUserInput[] | Prisma.UsersOnChatsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UsersOnChatsCreateOrConnectWithoutUserInput | Prisma.UsersOnChatsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UsersOnChatsCreateManyUserInputEnvelope
  connect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
}

export type UsersOnChatsUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutUserInput, Prisma.UsersOnChatsUncheckedCreateWithoutUserInput> | Prisma.UsersOnChatsCreateWithoutUserInput[] | Prisma.UsersOnChatsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UsersOnChatsCreateOrConnectWithoutUserInput | Prisma.UsersOnChatsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UsersOnChatsCreateManyUserInputEnvelope
  connect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
}

export type UsersOnChatsUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutUserInput, Prisma.UsersOnChatsUncheckedCreateWithoutUserInput> | Prisma.UsersOnChatsCreateWithoutUserInput[] | Prisma.UsersOnChatsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UsersOnChatsCreateOrConnectWithoutUserInput | Prisma.UsersOnChatsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UsersOnChatsUpsertWithWhereUniqueWithoutUserInput | Prisma.UsersOnChatsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UsersOnChatsCreateManyUserInputEnvelope
  set?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  disconnect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  delete?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  connect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  update?: Prisma.UsersOnChatsUpdateWithWhereUniqueWithoutUserInput | Prisma.UsersOnChatsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UsersOnChatsUpdateManyWithWhereWithoutUserInput | Prisma.UsersOnChatsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UsersOnChatsScalarWhereInput | Prisma.UsersOnChatsScalarWhereInput[]
}

export type UsersOnChatsUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutUserInput, Prisma.UsersOnChatsUncheckedCreateWithoutUserInput> | Prisma.UsersOnChatsCreateWithoutUserInput[] | Prisma.UsersOnChatsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UsersOnChatsCreateOrConnectWithoutUserInput | Prisma.UsersOnChatsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UsersOnChatsUpsertWithWhereUniqueWithoutUserInput | Prisma.UsersOnChatsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UsersOnChatsCreateManyUserInputEnvelope
  set?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  disconnect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  delete?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  connect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  update?: Prisma.UsersOnChatsUpdateWithWhereUniqueWithoutUserInput | Prisma.UsersOnChatsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UsersOnChatsUpdateManyWithWhereWithoutUserInput | Prisma.UsersOnChatsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UsersOnChatsScalarWhereInput | Prisma.UsersOnChatsScalarWhereInput[]
}

export type UsersOnChatsCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutChatInput, Prisma.UsersOnChatsUncheckedCreateWithoutChatInput> | Prisma.UsersOnChatsCreateWithoutChatInput[] | Prisma.UsersOnChatsUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.UsersOnChatsCreateOrConnectWithoutChatInput | Prisma.UsersOnChatsCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.UsersOnChatsCreateManyChatInputEnvelope
  connect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
}

export type UsersOnChatsUncheckedCreateNestedManyWithoutChatInput = {
  create?: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutChatInput, Prisma.UsersOnChatsUncheckedCreateWithoutChatInput> | Prisma.UsersOnChatsCreateWithoutChatInput[] | Prisma.UsersOnChatsUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.UsersOnChatsCreateOrConnectWithoutChatInput | Prisma.UsersOnChatsCreateOrConnectWithoutChatInput[]
  createMany?: Prisma.UsersOnChatsCreateManyChatInputEnvelope
  connect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
}

export type UsersOnChatsUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutChatInput, Prisma.UsersOnChatsUncheckedCreateWithoutChatInput> | Prisma.UsersOnChatsCreateWithoutChatInput[] | Prisma.UsersOnChatsUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.UsersOnChatsCreateOrConnectWithoutChatInput | Prisma.UsersOnChatsCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.UsersOnChatsUpsertWithWhereUniqueWithoutChatInput | Prisma.UsersOnChatsUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.UsersOnChatsCreateManyChatInputEnvelope
  set?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  disconnect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  delete?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  connect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  update?: Prisma.UsersOnChatsUpdateWithWhereUniqueWithoutChatInput | Prisma.UsersOnChatsUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.UsersOnChatsUpdateManyWithWhereWithoutChatInput | Prisma.UsersOnChatsUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.UsersOnChatsScalarWhereInput | Prisma.UsersOnChatsScalarWhereInput[]
}

export type UsersOnChatsUncheckedUpdateManyWithoutChatNestedInput = {
  create?: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutChatInput, Prisma.UsersOnChatsUncheckedCreateWithoutChatInput> | Prisma.UsersOnChatsCreateWithoutChatInput[] | Prisma.UsersOnChatsUncheckedCreateWithoutChatInput[]
  connectOrCreate?: Prisma.UsersOnChatsCreateOrConnectWithoutChatInput | Prisma.UsersOnChatsCreateOrConnectWithoutChatInput[]
  upsert?: Prisma.UsersOnChatsUpsertWithWhereUniqueWithoutChatInput | Prisma.UsersOnChatsUpsertWithWhereUniqueWithoutChatInput[]
  createMany?: Prisma.UsersOnChatsCreateManyChatInputEnvelope
  set?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  disconnect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  delete?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  connect?: Prisma.UsersOnChatsWhereUniqueInput | Prisma.UsersOnChatsWhereUniqueInput[]
  update?: Prisma.UsersOnChatsUpdateWithWhereUniqueWithoutChatInput | Prisma.UsersOnChatsUpdateWithWhereUniqueWithoutChatInput[]
  updateMany?: Prisma.UsersOnChatsUpdateManyWithWhereWithoutChatInput | Prisma.UsersOnChatsUpdateManyWithWhereWithoutChatInput[]
  deleteMany?: Prisma.UsersOnChatsScalarWhereInput | Prisma.UsersOnChatsScalarWhereInput[]
}

export type UsersOnChatsCreateWithoutUserInput = {
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
  chat: Prisma.ChatCreateNestedOneWithoutUsersInput
}

export type UsersOnChatsUncheckedCreateWithoutUserInput = {
  chatId: string
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
}

export type UsersOnChatsCreateOrConnectWithoutUserInput = {
  where: Prisma.UsersOnChatsWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutUserInput, Prisma.UsersOnChatsUncheckedCreateWithoutUserInput>
}

export type UsersOnChatsCreateManyUserInputEnvelope = {
  data: Prisma.UsersOnChatsCreateManyUserInput | Prisma.UsersOnChatsCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UsersOnChatsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UsersOnChatsWhereUniqueInput
  update: Prisma.XOR<Prisma.UsersOnChatsUpdateWithoutUserInput, Prisma.UsersOnChatsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutUserInput, Prisma.UsersOnChatsUncheckedCreateWithoutUserInput>
}

export type UsersOnChatsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UsersOnChatsWhereUniqueInput
  data: Prisma.XOR<Prisma.UsersOnChatsUpdateWithoutUserInput, Prisma.UsersOnChatsUncheckedUpdateWithoutUserInput>
}

export type UsersOnChatsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UsersOnChatsScalarWhereInput
  data: Prisma.XOR<Prisma.UsersOnChatsUpdateManyMutationInput, Prisma.UsersOnChatsUncheckedUpdateManyWithoutUserInput>
}

export type UsersOnChatsScalarWhereInput = {
  AND?: Prisma.UsersOnChatsScalarWhereInput | Prisma.UsersOnChatsScalarWhereInput[]
  OR?: Prisma.UsersOnChatsScalarWhereInput[]
  NOT?: Prisma.UsersOnChatsScalarWhereInput | Prisma.UsersOnChatsScalarWhereInput[]
  chatId?: Prisma.StringFilter<"UsersOnChats"> | string
  userId?: Prisma.StringFilter<"UsersOnChats"> | string
  newMessagesCount?: Prisma.IntFilter<"UsersOnChats"> | number
  createdAt?: Prisma.DateTimeFilter<"UsersOnChats"> | Date | string
  lastSeenAt?: Prisma.DateTimeFilter<"UsersOnChats"> | Date | string
}

export type UsersOnChatsCreateWithoutChatInput = {
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutChatsInput
}

export type UsersOnChatsUncheckedCreateWithoutChatInput = {
  userId: string
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
}

export type UsersOnChatsCreateOrConnectWithoutChatInput = {
  where: Prisma.UsersOnChatsWhereUniqueInput
  create: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutChatInput, Prisma.UsersOnChatsUncheckedCreateWithoutChatInput>
}

export type UsersOnChatsCreateManyChatInputEnvelope = {
  data: Prisma.UsersOnChatsCreateManyChatInput | Prisma.UsersOnChatsCreateManyChatInput[]
  skipDuplicates?: boolean
}

export type UsersOnChatsUpsertWithWhereUniqueWithoutChatInput = {
  where: Prisma.UsersOnChatsWhereUniqueInput
  update: Prisma.XOR<Prisma.UsersOnChatsUpdateWithoutChatInput, Prisma.UsersOnChatsUncheckedUpdateWithoutChatInput>
  create: Prisma.XOR<Prisma.UsersOnChatsCreateWithoutChatInput, Prisma.UsersOnChatsUncheckedCreateWithoutChatInput>
}

export type UsersOnChatsUpdateWithWhereUniqueWithoutChatInput = {
  where: Prisma.UsersOnChatsWhereUniqueInput
  data: Prisma.XOR<Prisma.UsersOnChatsUpdateWithoutChatInput, Prisma.UsersOnChatsUncheckedUpdateWithoutChatInput>
}

export type UsersOnChatsUpdateManyWithWhereWithoutChatInput = {
  where: Prisma.UsersOnChatsScalarWhereInput
  data: Prisma.XOR<Prisma.UsersOnChatsUpdateManyMutationInput, Prisma.UsersOnChatsUncheckedUpdateManyWithoutChatInput>
}

export type UsersOnChatsCreateManyUserInput = {
  chatId: string
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
}

export type UsersOnChatsUpdateWithoutUserInput = {
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chat?: Prisma.ChatUpdateOneRequiredWithoutUsersNestedInput
}

export type UsersOnChatsUncheckedUpdateWithoutUserInput = {
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsersOnChatsUncheckedUpdateManyWithoutUserInput = {
  chatId?: Prisma.StringFieldUpdateOperationsInput | string
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsersOnChatsCreateManyChatInput = {
  userId: string
  newMessagesCount?: number
  createdAt?: Date | string
  lastSeenAt?: Date | string
}

export type UsersOnChatsUpdateWithoutChatInput = {
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutChatsNestedInput
}

export type UsersOnChatsUncheckedUpdateWithoutChatInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsersOnChatsUncheckedUpdateManyWithoutChatInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  newMessagesCount?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  lastSeenAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UsersOnChatsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  chatId?: boolean
  userId?: boolean
  newMessagesCount?: boolean
  createdAt?: boolean
  lastSeenAt?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usersOnChats"]>

export type UsersOnChatsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  chatId?: boolean
  userId?: boolean
  newMessagesCount?: boolean
  createdAt?: boolean
  lastSeenAt?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usersOnChats"]>

export type UsersOnChatsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  chatId?: boolean
  userId?: boolean
  newMessagesCount?: boolean
  createdAt?: boolean
  lastSeenAt?: boolean
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usersOnChats"]>

export type UsersOnChatsSelectScalar = {
  chatId?: boolean
  userId?: boolean
  newMessagesCount?: boolean
  createdAt?: boolean
  lastSeenAt?: boolean
}

export type UsersOnChatsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"chatId" | "userId" | "newMessagesCount" | "createdAt" | "lastSeenAt", ExtArgs["result"]["usersOnChats"]>
export type UsersOnChatsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UsersOnChatsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UsersOnChatsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chat?: boolean | Prisma.ChatDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UsersOnChatsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UsersOnChats"
  objects: {
    chat: Prisma.$ChatPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    chatId: string
    userId: string
    newMessagesCount: number
    createdAt: Date
    lastSeenAt: Date
  }, ExtArgs["result"]["usersOnChats"]>
  composites: {}
}

export type UsersOnChatsGetPayload<S extends boolean | null | undefined | UsersOnChatsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload, S>

export type UsersOnChatsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UsersOnChatsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UsersOnChatsCountAggregateInputType | true
  }

export interface UsersOnChatsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UsersOnChats'], meta: { name: 'UsersOnChats' } }
  /**
   * Find zero or one UsersOnChats that matches the filter.
   * @param {UsersOnChatsFindUniqueArgs} args - Arguments to find a UsersOnChats
   * @example
   * // Get one UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UsersOnChatsFindUniqueArgs>(args: Prisma.SelectSubset<T, UsersOnChatsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UsersOnChatsClient<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UsersOnChats that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UsersOnChatsFindUniqueOrThrowArgs} args - Arguments to find a UsersOnChats
   * @example
   * // Get one UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UsersOnChatsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UsersOnChatsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsersOnChatsClient<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UsersOnChats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersOnChatsFindFirstArgs} args - Arguments to find a UsersOnChats
   * @example
   * // Get one UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UsersOnChatsFindFirstArgs>(args?: Prisma.SelectSubset<T, UsersOnChatsFindFirstArgs<ExtArgs>>): Prisma.Prisma__UsersOnChatsClient<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UsersOnChats that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersOnChatsFindFirstOrThrowArgs} args - Arguments to find a UsersOnChats
   * @example
   * // Get one UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UsersOnChatsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UsersOnChatsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsersOnChatsClient<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UsersOnChats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersOnChatsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.findMany()
   * 
   * // Get first 10 UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.findMany({ take: 10 })
   * 
   * // Only select the `chatId`
   * const usersOnChatsWithChatIdOnly = await prisma.usersOnChats.findMany({ select: { chatId: true } })
   * 
   */
  findMany<T extends UsersOnChatsFindManyArgs>(args?: Prisma.SelectSubset<T, UsersOnChatsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UsersOnChats.
   * @param {UsersOnChatsCreateArgs} args - Arguments to create a UsersOnChats.
   * @example
   * // Create one UsersOnChats
   * const UsersOnChats = await prisma.usersOnChats.create({
   *   data: {
   *     // ... data to create a UsersOnChats
   *   }
   * })
   * 
   */
  create<T extends UsersOnChatsCreateArgs>(args: Prisma.SelectSubset<T, UsersOnChatsCreateArgs<ExtArgs>>): Prisma.Prisma__UsersOnChatsClient<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UsersOnChats.
   * @param {UsersOnChatsCreateManyArgs} args - Arguments to create many UsersOnChats.
   * @example
   * // Create many UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UsersOnChatsCreateManyArgs>(args?: Prisma.SelectSubset<T, UsersOnChatsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UsersOnChats and returns the data saved in the database.
   * @param {UsersOnChatsCreateManyAndReturnArgs} args - Arguments to create many UsersOnChats.
   * @example
   * // Create many UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UsersOnChats and only return the `chatId`
   * const usersOnChatsWithChatIdOnly = await prisma.usersOnChats.createManyAndReturn({
   *   select: { chatId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UsersOnChatsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UsersOnChatsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UsersOnChats.
   * @param {UsersOnChatsDeleteArgs} args - Arguments to delete one UsersOnChats.
   * @example
   * // Delete one UsersOnChats
   * const UsersOnChats = await prisma.usersOnChats.delete({
   *   where: {
   *     // ... filter to delete one UsersOnChats
   *   }
   * })
   * 
   */
  delete<T extends UsersOnChatsDeleteArgs>(args: Prisma.SelectSubset<T, UsersOnChatsDeleteArgs<ExtArgs>>): Prisma.Prisma__UsersOnChatsClient<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UsersOnChats.
   * @param {UsersOnChatsUpdateArgs} args - Arguments to update one UsersOnChats.
   * @example
   * // Update one UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UsersOnChatsUpdateArgs>(args: Prisma.SelectSubset<T, UsersOnChatsUpdateArgs<ExtArgs>>): Prisma.Prisma__UsersOnChatsClient<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UsersOnChats.
   * @param {UsersOnChatsDeleteManyArgs} args - Arguments to filter UsersOnChats to delete.
   * @example
   * // Delete a few UsersOnChats
   * const { count } = await prisma.usersOnChats.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UsersOnChatsDeleteManyArgs>(args?: Prisma.SelectSubset<T, UsersOnChatsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UsersOnChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersOnChatsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UsersOnChatsUpdateManyArgs>(args: Prisma.SelectSubset<T, UsersOnChatsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UsersOnChats and returns the data updated in the database.
   * @param {UsersOnChatsUpdateManyAndReturnArgs} args - Arguments to update many UsersOnChats.
   * @example
   * // Update many UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UsersOnChats and only return the `chatId`
   * const usersOnChatsWithChatIdOnly = await prisma.usersOnChats.updateManyAndReturn({
   *   select: { chatId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UsersOnChatsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UsersOnChatsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UsersOnChats.
   * @param {UsersOnChatsUpsertArgs} args - Arguments to update or create a UsersOnChats.
   * @example
   * // Update or create a UsersOnChats
   * const usersOnChats = await prisma.usersOnChats.upsert({
   *   create: {
   *     // ... data to create a UsersOnChats
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UsersOnChats we want to update
   *   }
   * })
   */
  upsert<T extends UsersOnChatsUpsertArgs>(args: Prisma.SelectSubset<T, UsersOnChatsUpsertArgs<ExtArgs>>): Prisma.Prisma__UsersOnChatsClient<runtime.Types.Result.GetResult<Prisma.$UsersOnChatsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UsersOnChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersOnChatsCountArgs} args - Arguments to filter UsersOnChats to count.
   * @example
   * // Count the number of UsersOnChats
   * const count = await prisma.usersOnChats.count({
   *   where: {
   *     // ... the filter for the UsersOnChats we want to count
   *   }
   * })
  **/
  count<T extends UsersOnChatsCountArgs>(
    args?: Prisma.Subset<T, UsersOnChatsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsersOnChatsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UsersOnChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersOnChatsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UsersOnChatsAggregateArgs>(args: Prisma.Subset<T, UsersOnChatsAggregateArgs>): Prisma.PrismaPromise<GetUsersOnChatsAggregateType<T>>

  /**
   * Group by UsersOnChats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsersOnChatsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UsersOnChatsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UsersOnChatsGroupByArgs['orderBy'] }
      : { orderBy?: UsersOnChatsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UsersOnChatsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUsersOnChatsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UsersOnChats model
 */
readonly fields: UsersOnChatsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UsersOnChats.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UsersOnChatsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chat<T extends Prisma.ChatDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChatDefaultArgs<ExtArgs>>): Prisma.Prisma__ChatClient<runtime.Types.Result.GetResult<Prisma.$ChatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UsersOnChats model
 */
export interface UsersOnChatsFieldRefs {
  readonly chatId: Prisma.FieldRef<"UsersOnChats", 'String'>
  readonly userId: Prisma.FieldRef<"UsersOnChats", 'String'>
  readonly newMessagesCount: Prisma.FieldRef<"UsersOnChats", 'Int'>
  readonly createdAt: Prisma.FieldRef<"UsersOnChats", 'DateTime'>
  readonly lastSeenAt: Prisma.FieldRef<"UsersOnChats", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UsersOnChats findUnique
 */
export type UsersOnChatsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * Filter, which UsersOnChats to fetch.
   */
  where: Prisma.UsersOnChatsWhereUniqueInput
}

/**
 * UsersOnChats findUniqueOrThrow
 */
export type UsersOnChatsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * Filter, which UsersOnChats to fetch.
   */
  where: Prisma.UsersOnChatsWhereUniqueInput
}

/**
 * UsersOnChats findFirst
 */
export type UsersOnChatsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * Filter, which UsersOnChats to fetch.
   */
  where?: Prisma.UsersOnChatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UsersOnChats to fetch.
   */
  orderBy?: Prisma.UsersOnChatsOrderByWithRelationInput | Prisma.UsersOnChatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UsersOnChats.
   */
  cursor?: Prisma.UsersOnChatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UsersOnChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UsersOnChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UsersOnChats.
   */
  distinct?: Prisma.UsersOnChatsScalarFieldEnum | Prisma.UsersOnChatsScalarFieldEnum[]
}

/**
 * UsersOnChats findFirstOrThrow
 */
export type UsersOnChatsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * Filter, which UsersOnChats to fetch.
   */
  where?: Prisma.UsersOnChatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UsersOnChats to fetch.
   */
  orderBy?: Prisma.UsersOnChatsOrderByWithRelationInput | Prisma.UsersOnChatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UsersOnChats.
   */
  cursor?: Prisma.UsersOnChatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UsersOnChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UsersOnChats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UsersOnChats.
   */
  distinct?: Prisma.UsersOnChatsScalarFieldEnum | Prisma.UsersOnChatsScalarFieldEnum[]
}

/**
 * UsersOnChats findMany
 */
export type UsersOnChatsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * Filter, which UsersOnChats to fetch.
   */
  where?: Prisma.UsersOnChatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UsersOnChats to fetch.
   */
  orderBy?: Prisma.UsersOnChatsOrderByWithRelationInput | Prisma.UsersOnChatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UsersOnChats.
   */
  cursor?: Prisma.UsersOnChatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UsersOnChats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UsersOnChats.
   */
  skip?: number
  distinct?: Prisma.UsersOnChatsScalarFieldEnum | Prisma.UsersOnChatsScalarFieldEnum[]
}

/**
 * UsersOnChats create
 */
export type UsersOnChatsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * The data needed to create a UsersOnChats.
   */
  data: Prisma.XOR<Prisma.UsersOnChatsCreateInput, Prisma.UsersOnChatsUncheckedCreateInput>
}

/**
 * UsersOnChats createMany
 */
export type UsersOnChatsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UsersOnChats.
   */
  data: Prisma.UsersOnChatsCreateManyInput | Prisma.UsersOnChatsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UsersOnChats createManyAndReturn
 */
export type UsersOnChatsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * The data used to create many UsersOnChats.
   */
  data: Prisma.UsersOnChatsCreateManyInput | Prisma.UsersOnChatsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UsersOnChats update
 */
export type UsersOnChatsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * The data needed to update a UsersOnChats.
   */
  data: Prisma.XOR<Prisma.UsersOnChatsUpdateInput, Prisma.UsersOnChatsUncheckedUpdateInput>
  /**
   * Choose, which UsersOnChats to update.
   */
  where: Prisma.UsersOnChatsWhereUniqueInput
}

/**
 * UsersOnChats updateMany
 */
export type UsersOnChatsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UsersOnChats.
   */
  data: Prisma.XOR<Prisma.UsersOnChatsUpdateManyMutationInput, Prisma.UsersOnChatsUncheckedUpdateManyInput>
  /**
   * Filter which UsersOnChats to update
   */
  where?: Prisma.UsersOnChatsWhereInput
  /**
   * Limit how many UsersOnChats to update.
   */
  limit?: number
}

/**
 * UsersOnChats updateManyAndReturn
 */
export type UsersOnChatsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * The data used to update UsersOnChats.
   */
  data: Prisma.XOR<Prisma.UsersOnChatsUpdateManyMutationInput, Prisma.UsersOnChatsUncheckedUpdateManyInput>
  /**
   * Filter which UsersOnChats to update
   */
  where?: Prisma.UsersOnChatsWhereInput
  /**
   * Limit how many UsersOnChats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UsersOnChats upsert
 */
export type UsersOnChatsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * The filter to search for the UsersOnChats to update in case it exists.
   */
  where: Prisma.UsersOnChatsWhereUniqueInput
  /**
   * In case the UsersOnChats found by the `where` argument doesn't exist, create a new UsersOnChats with this data.
   */
  create: Prisma.XOR<Prisma.UsersOnChatsCreateInput, Prisma.UsersOnChatsUncheckedCreateInput>
  /**
   * In case the UsersOnChats was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UsersOnChatsUpdateInput, Prisma.UsersOnChatsUncheckedUpdateInput>
}

/**
 * UsersOnChats delete
 */
export type UsersOnChatsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
  /**
   * Filter which UsersOnChats to delete.
   */
  where: Prisma.UsersOnChatsWhereUniqueInput
}

/**
 * UsersOnChats deleteMany
 */
export type UsersOnChatsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UsersOnChats to delete
   */
  where?: Prisma.UsersOnChatsWhereInput
  /**
   * Limit how many UsersOnChats to delete.
   */
  limit?: number
}

/**
 * UsersOnChats without action
 */
export type UsersOnChatsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsersOnChats
   */
  select?: Prisma.UsersOnChatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UsersOnChats
   */
  omit?: Prisma.UsersOnChatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsersOnChatsInclude<ExtArgs> | null
}
