// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"billing-service/internal/domain/service/config"
	"billing-service/internal/infrastructure/service/config_impl"
)

// Injectors from wire.go:

func newContainer() (config_service.ConfigService, func(), error) {
	configServiceImpl := config_service_impl.NewConfigService()
	return configServiceImpl, func() {
	}, nil
}

// wire.go:

type Container struct {
	ConfigService *config_service.ConfigService
}
