// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"billing-service/internal/domain/service/config"
	"billing-service/internal/infrastructure/service/config_impl"
)

// Injectors from wire.go:

func newContainer() (*Container, func(), error) {
	configServiceImpl := config_service_impl.NewConfigService()
	container := &Container{
		ConfigService: configServiceImpl,
	}
	return container, func() {
	}, nil
}

// wire.go:

type Container struct {
	ConfigService config_service.ConfigService
}
