// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: map_service.proto
// Protobuf Java Version: 4.27.0

package com.tinder.grpc.map;

public interface GetGeocodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:map.GetGeocodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitude = 1;</code>
   * @return The latitude.
   */
  double getLatitude();

  /**
   * <code>double longitude = 2;</code>
   * @return The longitude.
   */
  double getLongitude();
}
