// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: map_service.proto
// Protobuf Java Version: 4.27.0

package com.tinder.grpc.map;

public final class MapServiceOuterClass {
  private MapServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 0,
      /* suffix= */ "",
      MapServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_map_GetGeocodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_map_GetGeocodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_map_Geocode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_map_Geocode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021map_service.proto\022\003map\"8\n\021GetGeocodeRe" +
      "quest\022\020\n\010latitude\030\001 \001(\001\022\021\n\tlongitude\030\002 \001" +
      "(\001\"(\n\007Geocode\022\014\n\004name\030\001 \001(\t\022\017\n\007address\030\002" +
      " \001(\t2@\n\nMapService\0222\n\nGetGeocode\022\026.map.G" +
      "etGeocodeRequest\032\014.map.GeocodeB\027\n\023com.ti" +
      "nder.grpc.mapP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_map_GetGeocodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_map_GetGeocodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_map_GetGeocodeRequest_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_map_Geocode_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_map_Geocode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_map_Geocode_descriptor,
        new java.lang.String[] { "Name", "Address", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
