name: billing-service-ci

on:
  push:
    paths:
      - 'billing-service/**'

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/golang-service-ci
        with:
          service-path: ./billing-service
          with-migration: true
          main-file-root-path: ./cmd/main
