name: map-service-ci

on:
  push:
    paths:
      - 'map-service/**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
      - name: Install dependencies
        run: mvn dependency:go-offline
      - name: Run tests
        run: mvn test
      - name: Build JAR
        run: mvn clean package -DskipTests -Dmaven.test.skip=true
