name: subscription-service-ci

on:
  push:
    paths:
      - 'subscription-service/**'

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/golang-service-ci
        with:
          service-path: ./subscription-service
          with-migration: true
          main-file-root-path: ./cmd/main/main.go ./cmd/main/wire_gen.go
